Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2019-09, with the labels that each got.

#631 Update README.md
  README.md
Labels: Documentation

#629 Fix `{build.mcu}` definition
  boards.txt
  platform.txt
Labels: Arduino compatibility, Enhancement, Fix

#632 Rename DIYMROE to DIYMORE
  CI/build/conf/cores_config.json
  boards.txt
  variants/DIYMORE_F407VGT/PeripheralPins.c
  variants/DIYMORE_F407VGT/PinNamesVar.h
  variants/DIYMORE_F407VGT/ldscript.ld
  variants/DIYMORE_F407VGT/variant.cpp
  variants/DIYMORE_F407VGT/variant.h
Labels: Fix

#641 Fix callbacks array init. Move nptr check in the start of CCcb
  cores/arduino/HardwareTimer.cpp
Labels: Bug, Fix

#645 SoftwareSerial implementation
  libraries/SoftwareSerial/examples/SoftwareSerialExample/SoftwareSerialExample.ino
  libraries/SoftwareSerial/examples/TwoPortReceive/TwoPortReceive.ino
  libraries/SoftwareSerial/keywords.txt
  libraries/SoftwareSerial/library.properties
  libraries/SoftwareSerial/src/SoftwareSerial.cpp
  libraries/SoftwareSerial/src/SoftwareSerial.h
Labels: Arduino compatibility, Enhancement, New feature

#590 Added the repeated-start feature in I2C driver
  cores/arduino/stm32/twi.c
  libraries/Wire/src/Wire.cpp
Labels: Enhancement, New feature

#647 Port STM32L051 or module RHF76-052
  boards.txt
  variants/RHF76_052/PeripheralPins.c
  variants/RHF76_052/PinNamesVar.h
  variants/RHF76_052/ldscript.ld
  variants/RHF76_052/variant.cpp
  variants/RHF76_052/variant.h
Labels: New variant

#655 Update Nucleo H743ZI(2) variant
  boards.txt
  variants/NUCLEO_H743ZI/ldscript.ld
  variants/NUCLEO_H743ZI/variant.cpp
  variants/NUCLEO_H743ZI/variant.h
Labels: Enhancement

#657 [USB] Fix endpoints configurations
  cores/arduino/stm32/usb/cdc/usbd_cdc.h
  cores/arduino/stm32/usb/cdc/usbd_cdc_if.h
  cores/arduino/stm32/usb/hid/usbd_hid_composite.h
  cores/arduino/stm32/usb/usbd_conf.c
  cores/arduino/stm32/usb/usbd_ep_conf.c
  cores/arduino/stm32/usb/usbd_ep_conf.h
Labels: Enhancement, Fix

#663 Revert "Added the repeated-start feature in I2C driver"
  cores/arduino/stm32/twi.c
  libraries/Wire/src/Wire.cpp
Labels: Bug, Fix

#670 [USB] Fix EPO STALL issue in STM32 USB Device library
  system/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
Labels: Fix

#673 Add NUCLEO-L452RE-P support
  README.md
  boards.txt
  variants/NUCLEO_L452RE/PeripheralPins.c
  variants/NUCLEO_L452RE/ldscript.ld
  variants/NUCLEO_L452RE/variant.cpp
  variants/NUCLEO_L452RE/variant.h
Labels: New variant
