Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2019-02, with the labels that each got.

#434 [Nucleo L452RE] Add support
  boards.txt
  variants/NUCLEO_L452RE/PeripheralPins.c
  variants/NUCLEO_L452RE/PinNamesVar.h
  variants/NUCLEO_L452RE/ldscript.ld
  variants/NUCLEO_L452RE/stm32l4xx_hal_conf.h
  variants/NUCLEO_L452RE/variant.cpp
  variants/NUCLEO_L452RE/variant.h
Labels: New variant

#435 [dtostrf] Fix missing leading zeros in decimal part
  cores/arduino/avr/dtostrf.c
Labels: Bug, Fix

#426 [USBD] Force re-enumeration
  cores/arduino/stm32/usb/usbd_conf.c
  cores/arduino/stm32/usb/usbd_if.c
  cores/arduino/stm32/usb/usbd_if.h
  variants/MAPLEMINI_F103CB/variant.h
Labels: Enhancement

#441 Add STM32 core version
  cores/arduino/stm32/stm32_def.h
Labels: Enhancement

#439 True PMA correction
  cores/arduino/stm32/usb/usbd_conf.c
Labels: Bug, Fix

#443 Update STM32L0xx HAL Drivers to v1.10.1
  system/Drivers/STM32L0xx_HAL_Driver/Inc/stm32l0xx_hal_conf_template.h
  system/Drivers/STM32L0xx_HAL_Driver/Inc/stm32l0xx_hal_spi.h
  system/Drivers/STM32L0xx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c
  system/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.c
  system/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.c
  system/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c
  system/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_spi.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement

#432 Add Sparky V1 Variant, modify boards.txt
  boards.txt
  variants/SPARKY_F303CC/PeripheralPins.c
  variants/SPARKY_F303CC/PinNamesVar.h
  variants/SPARKY_F303CC/ldscript.ld
  variants/SPARKY_F303CC/stm32f3xx_hal_conf.h
  variants/SPARKY_F303CC/variant.cpp
  variants/SPARKY_F303CC/variant.h
Labels: New variant

#452 Index review
  cores/arduino/stm32/rtc.c
  cores/arduino/stm32/timer.c
  cores/arduino/stm32/twi.c
  cores/arduino/stm32/uart.c
Labels: Enhancement, Fix

#442 [RTC] Avoid reset time after low power mode
  cores/arduino/board.h
  cores/arduino/stm32/backup.h
  cores/arduino/stm32/clock.c
  cores/arduino/stm32/rtc.c
  cores/arduino/stm32/rtc.h
Labels: New feature
