Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2019-11, with the labels that each got.

#737 Fix Nucleo G071RB analog pin issue
  cores/arduino/stm32/analog.cpp
  variants/NUCLEO_G071RB/PeripheralPins.c
  variants/NUCLEO_G071RB/variant.cpp
  variants/NUCLEO_G071RB/variant.h
Labels: Fix

#748 I2C Fix
  cores/arduino/stm32/twi.c
  cores/arduino/stm32/twi.h
  libraries/Wire/src/Wire.cpp
Labels: Arduino compatibility, Enhancement, Fix, New feature

#749 Fix single-pin half-duplex in SoftwareSerial::send
  libraries/SoftwareSerial/src/SoftwareSerial.cpp
Labels: Fix

#764 Add methods to check if there's an IRQ handler
  cores/arduino/HardwareTimer.cpp
  cores/arduino/HardwareTimer.h
Labels: Enhancement

#771 [Timer] Add getHandle function
  cores/arduino/HardwareTimer.cpp
  cores/arduino/HardwareTimer.h
Labels: Enhancement

#773 [NUCLEO_L073RZ] Enable USB clock
  variants/NUCLEO_L073RZ/variant.cpp
Labels: Enhancement

#774 MP1 update
  cores/arduino/stm32/analog.cpp
  platform.txt
  system/Middlewares/OpenAMP/libmetal/lib/include/metal/system/generic/condition.h
  system/Middlewares/OpenAMP/libmetal/lib/include/metal/system/generic/sys.h
  system/Middlewares/OpenAMP/libmetal/st_readme.txt
  system/Middlewares/OpenAMP/mw_if/app_if/openamp_conf_template.h
  system/Middlewares/OpenAMP/mw_if/platform_if/rsc_table_template.c
  system/Middlewares/OpenAMP/mw_if/st_readme.txt
  system/Middlewares/OpenAMP/open-amp/lib/include/openamp/rpmsg.h
  system/Middlewares/OpenAMP/open-amp/lib/rpmsg/rpmsg.c
  system/Middlewares/OpenAMP/open-amp/st_readme.txt
  variants/STM32MP157_DK/PeripheralPins.c
  variants/STM32MP157_DK/README.md
  variants/STM32MP157_DK/variant.cpp
Labels: Enhancement, Fix

#783 MP1 GPIO EXTI
  cores/arduino/stm32/interrupt.cpp
  cores/arduino/stm32/lock_resource.h
Labels: Fix

#786 Fix keyword literal for setRx and setTx
  keywords.txt
Labels: Fix

#780 Add printf to print class
  cores/arduino/Print.cpp
  cores/arduino/Print.h
Labels: Enhancement

#795 Harden Print::printf() method
  cores/arduino/Print.cpp
  cores/arduino/Print.h
  libraries/SrcWrapper/src/syscalls.c
Labels: Enhancement

#794 SPI: Fix prescaler at low baudrates
  cores/arduino/stm32/spi_com.c
Labels: Enhancement

#788 New board definition: Piconomix PX-HER0 board (STM32L072RB)
  boards.txt
  variants/PX_HER0/PeripheralPins.c
  variants/PX_HER0/PinNamesVar.h
  variants/PX_HER0/ldscript.ld
  variants/PX_HER0/variant.cpp
  variants/PX_HER0/variant.h
Labels: New variant
