Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2019-04, with the labels that each got.

#491 Update CMSIS and arm-none-eabi-gcc
  .travis.yml
  platform.txt
Labels: Enhancement

#473 PR #447 review
  cores/arduino/stm32/timer.c
  cores/arduino/stm32/timer.h
Labels: New feature

#501 Fix String::remove warning
  cores/arduino/WString.cpp
Labels: Fix

#500 Support custom Usb reenumerate
  cores/arduino/stm32/usb/usbd_if.c
  variants/MALYANM200_F103CB/variant.cpp
Labels: Enhancement

#502 [PR 496 rework] Disable USART IRQ in uart_write and uart_debug_write
  cores/arduino/HardwareSerial.cpp
  cores/arduino/HardwareSerial.h
  cores/arduino/stm32/uart.c
  cores/arduino/stm32/uart.h
Labels: Enhancement, Fix, Help wanted

#503 Re-evaluate interrupt priority values
  cores/arduino/stm32/interrupt.cpp
  cores/arduino/stm32/interrupt.h
  cores/arduino/stm32/rtc.c
  cores/arduino/stm32/rtc.h
  cores/arduino/stm32/timer.c
  cores/arduino/stm32/timer.h
  cores/arduino/stm32/twi.c
  cores/arduino/stm32/twi.h
  cores/arduino/stm32/uart.c
  cores/arduino/stm32/uart.h
  cores/arduino/stm32/usb/usbd_conf.c
  cores/arduino/stm32/usb/usbd_conf.h
Labels: Enhancement, Fix

#504 twi: fix copy-paste error
  cores/arduino/stm32/twi.c
Labels: Fix

#511 Add support for using -g3 compiler option
  platform.txt
Labels: Enhancement

#512 Fix to build with ISO C standard
  cores/arduino/avr/dtostrf.c
  cores/arduino/stm32/dwt.c
Labels: Enhancement
