Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2019-12, with the labels that each got.

#811 Fix usage of weak functions instead of harden one
  libraries/SrcWrapper/library.properties
  libraries/SrcWrapper/src/stm32/PortNames.c
  libraries/SrcWrapper/src/stm32/analog.cpp
  libraries/SrcWrapper/src/stm32/bootloader.c
  libraries/SrcWrapper/src/stm32/clock.c
  libraries/SrcWrapper/src/stm32/core_callback.c
  libraries/SrcWrapper/src/stm32/dwt.c
  libraries/SrcWrapper/src/stm32/hw_config.c
  libraries/SrcWrapper/src/stm32/interrupt.cpp
  libraries/SrcWrapper/src/stm32/lock_resource.c
  libraries/SrcWrapper/src/stm32/low_power.c
  libraries/SrcWrapper/src/stm32/pinmap.c
  libraries/SrcWrapper/src/stm32/rtc.c
  libraries/SrcWrapper/src/stm32/stm32_def.c
  libraries/SrcWrapper/src/stm32/stm32_eeprom.c
  libraries/SrcWrapper/src/stm32/system_stm32yyxx.c
  libraries/SrcWrapper/src/stm32/timer.c
  libraries/SrcWrapper/src/stm32/uart.c
Labels: Fix

#810 Added Elektor LoRa Node ( STM32F072 based )
  boards.txt
  variants/ELEKTOR_F072C8/PeripheralPins.c
  variants/ELEKTOR_F072C8/PinNamesVar.h
  variants/ELEKTOR_F072C8/ldscript.ld
  variants/ELEKTOR_F072C8/variant.cpp
  variants/ELEKTOR_F072C8/variant.h
Labels: New variant

#819 Moved from arm-none-eabi-gcc 8.2.1-1.7 to 9.2.1-1.1
  platform.txt
Labels: Enhancement

#806 HardwareTimer: rework internal mapping of arduino API to HAL/LL API
  cores/arduino/HardwareTimer.cpp
  cores/arduino/HardwareTimer.h
  cores/arduino/Tone.cpp
Labels: Enhancement, Fix

#814 Rework PWM_RESOLUTION
  cores/arduino/HardwareTimer.cpp
  cores/arduino/HardwareTimer.h
  cores/arduino/pins_arduino.h
  cores/arduino/stm32/analog.h
  cores/arduino/wiring_analog.c
  keywords.txt
  libraries/SrcWrapper/src/stm32/analog.cpp
  variants/ARMED_V1/variant.h
  variants/REMRAM_V1/variant.h
  variants/RUMBA32_F446VE/variant.h
Labels: Fix

#824 HardwareTimer: Fix STM32F1 specific gpio configuration in case of input
  cores/arduino/HardwareTimer.cpp
Labels: Fix

#826 Fix SPI pin matching check
  libraries/SPI/src/utility/spi_com.c
Labels: Fix

#828 New variant - Malyan M300 3D Printer
  boards.txt
  variants/MALYANMx00_F070CB/PeripheralPins.c
  variants/MALYANMx00_F070CB/PinNamesVar.h
  variants/MALYANMx00_F070CB/ldscript.ld
  variants/MALYANMx00_F070CB/startup_Mx00_f070xb.S
  variants/MALYANMx00_F070CB/variant.cpp
  variants/MALYANMx00_F070CB/variant.h
Labels: New variant

#829 Fix resolution
  cores/arduino/pins_arduino.h
  cores/arduino/stm32/analog.h
  cores/arduino/wiring_analog.c
  libraries/SrcWrapper/src/stm32/analog.cpp
  variants/BLACK_F407XX/variant.h
  variants/BLUE_F407VE_Mini/variant.h
  variants/board_template/variant.h
Labels: Arduino compatibility, Enhancement, Fix

#835 HardwareTimer: set callback before enabling interrupt
  cores/arduino/HardwareTimer.cpp
Labels: Fix

#838 Wire : New "begin" method for late call configuration
  libraries/Wire/src/Wire.cpp
  libraries/Wire/src/Wire.h
Labels: New feature

#837 new variant: PRNTRv2
  boards.txt
  variants/PRNTR_Vx/PeripheralPins.c
  variants/PRNTR_Vx/PinNamesVar.h
  variants/PRNTR_Vx/ldscript.ld
  variants/PRNTR_Vx/variant.cpp
  variants/PRNTR_Vx/variant.h
Labels: New variant

#840 Fix build issue when TIM module is disabled or only requested
  cores/arduino/stm32/analog.h
Labels: Fix
