Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2019-10, with the labels that each got.

#643 Add half-duplex support to HardwareSerial.
  cores/arduino/HardwareSerial.cpp
  cores/arduino/HardwareSerial.h
  cores/arduino/stm32/uart.c
  cores/arduino/stm32/uart.h
Labels: New feature

#693 Set TIM_OCMODE_INACTIVE when using mode TIMER_OUTPUT_COMPARE_INACTIVE
  cores/arduino/HardwareTimer.cpp
Labels: Fix

#685 Add CMSIS DSP support as built-in library
  boards.txt
  libraries/CMSIS_DSP/keywords.txt
  libraries/CMSIS_DSP/library.properties
  libraries/CMSIS_DSP/src/BasicMathFunctions/BasicMathFunctions.c
  libraries/CMSIS_DSP/src/CMSIS_DSP.h
  libraries/CMSIS_DSP/src/CommonTables/CommonTables.c
  libraries/CMSIS_DSP/src/ComplexMathFunctions/ComplexMathFunctions.c
  libraries/CMSIS_DSP/src/ControllerFunctions/ControllerFunctions.c
  libraries/CMSIS_DSP/src/FastMathFunctions/FastMathFunctions.c
  libraries/CMSIS_DSP/src/FilteringFunctions/FilteringFunctions.c
  libraries/CMSIS_DSP/src/MatrixFunctions/MatrixFunctions.c
  libraries/CMSIS_DSP/src/StatisticsFunctions/StatisticsFunctions.c
  libraries/CMSIS_DSP/src/SupportFunctions/SupportFunctions.c
  libraries/CMSIS_DSP/src/TransformFunctions/TransformFunctions.c
  platform.txt
Labels: Enhancement, Fix, New feature

#694 Enhance half-duplex support
  cores/arduino/HardwareSerial.cpp
  cores/arduino/HardwareSerial.h
  cores/arduino/stm32/uart.c
  keywords.txt
Labels: Enhancement, Fix

#703 Add scripts to wrap files
  CI/utils/gen_wrapper.sh
Labels: New feature

#704 Add PF0 / PF1 pins on STM32F030F4
  variants/DEMO_F030F4/variant.cpp
  variants/DEMO_F030F4/variant.h
Labels: Enhancement

#701 New board definition - Adafruit Feather STM32F405
  README.md
  boards.txt
  variants/FEATHER_F405/PeripheralPins.c
  variants/FEATHER_F405/PinNamesVar.h
  variants/FEATHER_F405/ldscript.ld
  variants/FEATHER_F405/variant.cpp
  variants/FEATHER_F405/variant.h
Labels: New variant

#709 Added ThunderPack board (STM32L0xx)
  boards.txt
  variants/THUNDER_PACK/PeripheralPins.c
  variants/THUNDER_PACK/PinNamesVar.h
  variants/THUNDER_PACK/ldscript.ld
  variants/THUNDER_PACK/readme.txt
  variants/THUNDER_PACK/variant.cpp
  variants/THUNDER_PACK/variant.h
Labels: New variant

#719 Add new official library.properties field for static linking flags in platform.txt compiler recipe.
  platform.txt
Labels: Arduino compatibility, Fix

#740 Fix TIM6_IRQn definition
  cores/arduino/stm32/timer.h
Labels: Fix

#744 [ADC] Fix ADC_InitTypeDef member for STM32F37xx
  cores/arduino/stm32/analog.cpp
Labels: Fix
