Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2019-03, with the labels that each got.

#466 Fixed error, when host send some buffer, less then minimum.
  cores/arduino/stm32/usb/cdc/usbd_cdc.c
  cores/arduino/stm32/usb/cdc/usbd_cdc.h
  cores/arduino/stm32/usb/cdc/usbd_cdc_if.c
  cores/arduino/stm32/usb/cdc/usbd_cdc_if.h
Labels: Bug, Fix

#468 Fix of error
  cores/arduino/stm32/usb/cdc/usbd_cdc_if.c
Labels: Bug, Fix

#456 Receive double buffering for STM32F1xx
  cores/arduino/stm32/usb/cdc/usbd_cdc.c
  cores/arduino/stm32/usb/cdc/usbd_cdc.h
  cores/arduino/stm32/usb/usbd_conf.c
  system/Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_ll_usb.h
  system/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd.c
  system/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.c
  system/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc/usbd_cdc.h
  system/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c
  system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_def.h
  system/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
  system/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c
Labels: Enhancement

#444 USBSerial would not block on write if the USB inteface is not connected
  cores/arduino/USBSerial.cpp
  cores/arduino/stm32/usb/cdc/usbd_cdc_if.c
  cores/arduino/stm32/usb/cdc/usbd_cdc_if.h
Labels: Bug, Fix

#469 [USB HID] Harden init
  cores/arduino/stm32/usb/hid/usbd_hid_composite_if.c
  cores/arduino/stm32/usb/hid/usbd_hid_composite_if.h
  libraries/Keyboard/src/Keyboard.cpp
  libraries/Mouse/src/Mouse.cpp
Labels: Bug, Fix

#475 Allow to change default PWM frequency
  cores/arduino/wiring_analog.c
  cores/arduino/wiring_analog.h
Labels: Enhancement

#480 Fix issue #478.
  cores/arduino/stm32/usb/cdc/usbd_cdc_if.c
Labels: Bug, Fix

#477 [Time] Review delay
  cores/arduino/board.h
  cores/arduino/stm32/clock.c
  cores/arduino/stm32/clock.h
  cores/arduino/stm32/dwt.c
  cores/arduino/stm32/dwt.h
  cores/arduino/stm32/hw_config.c
  cores/arduino/wiring_time.c
  cores/arduino/wiring_time.h
Labels: Bug, Enhancement, Fix

#484 Do not warn if start of section is changed
  platform.txt
Labels: Fix

#485 Moved from CMSIS 5.3.0 to 5.4.0
  .travis.yml
  platform.txt
Labels: Enhancement
