Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2019-06, with the labels that each got.

#535 Add dummy analogReference() for compatibility
  cores/arduino/wiring_analog.c
  cores/arduino/wiring_analog.h
Labels: Arduino compatibility

#539 Add ADC internal channels
  cores/arduino/pins_arduino.c
  cores/arduino/pins_arduino.h
  cores/arduino/stm32/PinNames.h
  cores/arduino/stm32/analog.c
  keywords.txt
Labels: Enhancement, Fix

#540 HID Bootloader v2.2 support
  boards.txt
  cores/arduino/stm32/backup.h
  cores/arduino/stm32/bootloader.c
  cores/arduino/stm32/bootloader.h
  platform.txt
  variants/DIYMROE_F407VGT/ldscript.ld
Labels: Enhancement

#541 [I2C] Add general call mode settings
  cores/arduino/stm32/twi.c
  cores/arduino/stm32/twi.h
  libraries/Wire/src/Wire.cpp
  libraries/Wire/src/Wire.h
Labels: Enhancement

#544 Add support of BlackPill F303CC
  README.md
  boards.txt
  variants/PILL_F103XX/PeripheralPins.c
  variants/PILL_F103XX/PinNamesVar.h
  variants/PILL_F103XX/ldscript.ld
  variants/PILL_F103XX/variant.cpp
  variants/PILL_F103XX/variant.h
  variants/PILL_F303XX/PeripheralPins.c
  variants/PILL_F303XX/PinNamesVar.h
  variants/PILL_F303XX/ldscript.ld
  variants/PILL_F303XX/variant.cpp
  variants/PILL_F303XX/variant.h
Labels: New variant
