Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2020-10, with the labels that each got.

#1202 [L1] Update STM32L1xx HAL Drivers to v1.4.2
  system/Drivers/STM32L1xx_HAL_Driver/README.md
  system/Drivers/STM32L1xx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal.c
  system/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_i2c.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement, Fix

#1203 adding missing i2c2 SCL pinmap for DISCO_F407G
  variants/DISCO_F407VG/PeripheralPins.c
Labels: Enhancement

#1184 Add requestFrom(uint8_t address, size_t quantity, bool sendStop)
  libraries/Wire/src/Wire.cpp
  libraries/Wire/src/Wire.h
Labels: Arduino compatibility

#1219 [SPI] Fix CS pin check
  libraries/SPI/src/SPI.cpp
  libraries/SPI/src/SPI.h
Labels: Bug, Fix

#1221 Wire fixes for repeated start(slave) and multiple .write in onRequestEvent()
  libraries/Wire/src/utility/twi.c
Labels: Enhancement, Fix

#1225 Update STM32 F4 and L1 HAL drivers
  system/Drivers/STM32F4xx_HAL_Driver/README.md
  system/Drivers/STM32F4xx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c
  system/Drivers/STM32L1xx_HAL_Driver/README.md
  system/Drivers/STM32L1xx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal.c
  system/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_i2c.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement, Fix
