Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2020-09, with the labels that each got.

#1165 [CI] Remove platformio-build.py from ignore paths
  .github/workflows/Continuous-Integration.yml
Labels: Enhancement

#1155 Moved from arm-none-eabi-gcc 9.3.1-1.1 to 9.3.1-1.2
  platform.txt
Labels: Fix

#1164 Update PlatformIO scripts
  .github/actions/pio-build/entrypoint.sh
  tools/platformio-build.py
Labels: Enhancement

#1161 fix IS_ADC_CHANNEL() bug on STM32F411xE variants
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_adc_ex.h
Labels: Fix

#1166 HardwareTimer: pause() need to call HAL API to restore HAL state
  cores/arduino/HardwareTimer.cpp
Labels: Fix

#1163 Update XXXXSPI pinmap array
  cores/arduino/stm32/PeripheralPins.h
  variants/B_L4S5I_IOT01A/PeripheralPins.c
  variants/B_L4S5I_IOT01A/variant.h
  variants/DAISY_SEED/PeripheralPins.c
  variants/DISCO_F413ZH/PeripheralPins.c
  variants/DISCO_F746NG/PeripheralPins.c
  variants/DISCO_L475VG_IOT/PeripheralPins.c
  variants/DISCO_L475VG_IOT/variant.h
  variants/FYSETC_S6/PeripheralPins.c
  variants/Generic_F412Rx/PeripheralPins.c
  variants/Generic_F446Rx/PeripheralPins.c
  variants/Generic_F4x3Rx/PeripheralPins.c
  variants/MKR_SHARKY/PeripheralPins.c
  variants/NUCLEO_F446RE/PeripheralPins.c
  variants/NUCLEO_F767ZI/PeripheralPins.c
  variants/NUCLEO_F7x6ZG/PeripheralPins.c
  variants/NUCLEO_G474RE/PeripheralPins.c
  variants/NUCLEO_H743ZI/PeripheralPins.c
  variants/NUCLEO_L412KB/PeripheralPins.c
  variants/NUCLEO_L432KC/PeripheralPins.c
  variants/NUCLEO_L433RC_P/PeripheralPins.c
  variants/NUCLEO_L452RE/PeripheralPins.c
  variants/NUCLEO_L476RG/PeripheralPins.c
  variants/NUCLEO_L496ZG/PeripheralPins.c
  variants/PNUCLEO_WB55RG/PeripheralPins.c
  variants/PYBSTICK26_PRO/PeripheralPins.c
  variants/REMRAM_V1/PeripheralPins.c
  variants/RUMBA32_F446VE/PeripheralPins.c
  variants/STM32MP157_DK/PeripheralPins.c
  variants/VAKE_F446VE/PeripheralPins.c
Labels: Enhancement

#1169 Update STM32F4 HAL drivers
  CI/utils/patch/HAL/F4/0001-F4-Fix-IS_ADC_CHANNEL.patch
  CI/utils/patch/HAL/F4/0001-F4-I2C-HAL-fix-generate-Start-only-once-Stop-is-fini.patch
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_fmpsmbus.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_hcd.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2c.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pcd.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_fmpi2c.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_i2c.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_usb.h
  system/Drivers/STM32F4xx_HAL_Driver/License.md
  system/Drivers/STM32F4xx_HAL_Driver/README.md
  system/Drivers/STM32F4xx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpi2c.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpsmbus.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement, Fix

#1171 Change ARMED tone and servo timers
  variants/ARMED_V1/variant.h
Labels: Enhancement

#1174 Fix flash latency for F4x5RG running full speed at 168MHz
  variants/Generic_F4x5RG/variant.cpp
Labels: Fix

#1173 Update Print/Stream API
  cores/arduino/Print.cpp
  cores/arduino/Print.h
  cores/arduino/Stream.h
Labels: Arduino compatibility, Fix

#1177 Update STM32L0 HAL drivers
  system/Drivers/STM32L0xx_HAL_Driver/Inc/stm32l0xx_hal.h
  system/Drivers/STM32L0xx_HAL_Driver/Inc/stm32l0xx_hal_gpio.h
  system/Drivers/STM32L0xx_HAL_Driver/Inc/stm32l0xx_hal_gpio_ex.h
  system/Drivers/STM32L0xx_HAL_Driver/Inc/stm32l0xx_hal_i2c.h
  system/Drivers/STM32L0xx_HAL_Driver/Inc/stm32l0xx_hal_i2c_ex.h
  system/Drivers/STM32L0xx_HAL_Driver/Inc/stm32l0xx_hal_pcd.h
  system/Drivers/STM32L0xx_HAL_Driver/Inc/stm32l0xx_hal_pcd_ex.h
  system/Drivers/STM32L0xx_HAL_Driver/Inc/stm32l0xx_hal_smbus.h
  system/Drivers/STM32L0xx_HAL_Driver/Inc/stm32l0xx_ll_gpio.h
  system/Drivers/STM32L0xx_HAL_Driver/Inc/stm32l0xx_ll_i2c.h
  system/Drivers/STM32L0xx_HAL_Driver/Inc/stm32l0xx_ll_usb.h
  system/Drivers/STM32L0xx_HAL_Driver/License.md
  system/Drivers/STM32L0xx_HAL_Driver/README.md
  system/Drivers/STM32L0xx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c
  system/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c
  system/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c
  system/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.c
  system/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pcd.c
  system/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pcd_ex.c
  system/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_smbus.c
  system/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_timebase_tim_template.c
  system/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_gpio.c
  system/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_usb.c
  system/Drivers/STM32L0xx_HAL_Driver/_htmresc/mini-st.css
  system/Drivers/STM32L0xx_HAL_Driver/_htmresc/st_logo.png
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement, Fix

#1182 Enable USB clock for Nucleo L053R8
  variants/NUCLEO_L053R8/variant.cpp
Labels: Enhancement

#1189 [G0] Fix USART IRQ handler
  libraries/SrcWrapper/src/stm32/uart.c
Labels: Fix
