Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2020-03, with the labels that each got.

#961 Define USER_BTN for BLACK PILL F411CE
  variants/Generic_F411Cx/variant.h
Labels: Enhancement

#965 Update pre-build recipe
  platform.txt
  system/extras/prebuild.sh
Labels: Enhancement, Fix

#969 Unified shell scripts naming
  platform.txt
Labels: Enhancement

#976 [CI] Build built-in libraries
  CI/build/arduino-cli.py
  CI/build/examples/BareMinimum/BareMinimum.ino
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc_ex.h
  variants/Generic_F410Cx/variant.h
  variants/Generic_F410Rx/variant.h
Labels: Enhancement, Fix

#974 Support for NUCLEO-F031K6 variant
  boards.txt
  variants/NUCLEO_F031K6/PeripheralPins.c
  variants/NUCLEO_F031K6/PinNamesVar.h
  variants/NUCLEO_F031K6/ldscript.ld
  variants/NUCLEO_F031K6/variant.cpp
  variants/NUCLEO_F031K6/variant.h
Labels: New variant

#892 Added functionality to pass custom parameter to HardwareTimer callback
  cores/arduino/HardwareTimer.cpp
  cores/arduino/HardwareTimer.h
  cores/arduino/Tone.cpp
  libraries/Servo/src/stm32/Servo.cpp
  libraries/SoftwareSerial/src/SoftwareSerial.cpp
  libraries/SoftwareSerial/src/SoftwareSerial.h
Labels: Enhancement

#982 [CI] Fix regression when checking error
  CI/build/arduino-cli.py
Labels: Fix

#979 NUCLEO_F303K8: remove PeripheralPins.c limitations
  variants/NUCLEO_F303K8/PeripheralPins.c
  variants/NUCLEO_F303K8/variant.cpp
  variants/NUCLEO_F303K8/variant.h
Labels: Enhancement, Fix

#978 HardwareTimer: replace comparison with NULL by implicit bool conversion
  cores/arduino/HardwareTimer.cpp
Labels: Enhancement

#987 Fix weaked serialEventRun() not being called
  cores/arduino/WSerial.cpp
  cores/arduino/WSerial.h
  cores/arduino/main.cpp
Labels: Fix

#988 [BMP upload] Fix compiler path
  platform.txt
Labels: Fix

#993 Fix weaked initVariant()declaration
  cores/arduino/Arduino.h
  cores/arduino/main.cpp
Labels: Fix

#766 [MP1] Add RPMsg virtual serial protocol support (VirtIOSerial)
  CI/build/conf/cores_config.json
  CI/build/conf/cores_config_ci.json
  CI/build/conf/cores_config_travis.json
  CI/build/examples/BareMinimum/BareMinimum.ino
  boards.txt
  cores/arduino/Print.cpp
  cores/arduino/VirtIOSerial.cpp
  cores/arduino/VirtIOSerial.h
  cores/arduino/WSerial.cpp
  cores/arduino/WSerial.h
  cores/arduino/stm32/OpenAMP/libmetal/device.c
  cores/arduino/stm32/OpenAMP/libmetal/generic/condition.c
  cores/arduino/stm32/OpenAMP/libmetal/generic/cortexm/sys.c
  cores/arduino/stm32/OpenAMP/libmetal/generic/generic_device.c
  cores/arduino/stm32/OpenAMP/libmetal/generic/generic_init.c
  cores/arduino/stm32/OpenAMP/libmetal/generic/generic_io.c
  cores/arduino/stm32/OpenAMP/libmetal/generic/generic_shmem.c
  cores/arduino/stm32/OpenAMP/libmetal/generic/time.c
  cores/arduino/stm32/OpenAMP/libmetal/init.c
  cores/arduino/stm32/OpenAMP/libmetal/io.c
  cores/arduino/stm32/OpenAMP/libmetal/log.c
  cores/arduino/stm32/OpenAMP/libmetal/shmem.c
  cores/arduino/stm32/OpenAMP/mbox_ipcc.c
  cores/arduino/stm32/OpenAMP/mbox_ipcc.h
  cores/arduino/stm32/OpenAMP/open-amp/remoteproc/remoteproc_virtio.c
  cores/arduino/stm32/OpenAMP/open-amp/rpmsg/rpmsg.c
  cores/arduino/stm32/OpenAMP/open-amp/rpmsg/rpmsg_virtio.c
  cores/arduino/stm32/OpenAMP/openamp.c
  cores/arduino/stm32/OpenAMP/openamp.h
  cores/arduino/stm32/OpenAMP/openamp_conf.h
  cores/arduino/stm32/OpenAMP/rsc_table.c
  cores/arduino/stm32/OpenAMP/rsc_table.h
  cores/arduino/stm32/OpenAMP/virt_uart.c
  cores/arduino/stm32/OpenAMP/virtio/virtio.c
  cores/arduino/stm32/OpenAMP/virtio/virtqueue.c
  cores/arduino/stm32/OpenAMP/virtio_buffer.c
  cores/arduino/stm32/OpenAMP/virtio_buffer.h
  cores/arduino/stm32/OpenAMP/virtio_config.h
  cores/arduino/stm32/OpenAMP/virtio_log.c
  cores/arduino/stm32/OpenAMP/virtio_log.h
  platform.txt
  variants/STM32MP157_DK/README.md
  variants/STM32MP157_DK/variant.h
Labels: New feature, Waiting feedback

#996 Support a .noinit section for variables
  platform.txt
  system/ldscript.ld
Labels: New feature

#984 Support for DISCO_F413ZH variant
  README.md
  boards.txt
  variants/DISCO_F413ZH/PeripheralPins.c
  variants/DISCO_F413ZH/PinNamesVar.h
  variants/DISCO_F413ZH/ldscript.ld
  variants/DISCO_F413ZH/variant.cpp
  variants/DISCO_F413ZH/variant.h
Labels: New variant

#1008 Fix typo in the Fysetc board definition
  boards.txt
Labels: Fix

#1014 Add support of NUCLEO_F746ZG and NUCLEO_F756ZG
  README.md
  boards.txt
  variants/NUCLEO_F7x6ZG/PeripheralPins.c
  variants/NUCLEO_F7x6ZG/PinNamesVar.h
  variants/NUCLEO_F7x6ZG/ldscript.ld
  variants/NUCLEO_F7x6ZG/variant.cpp
  variants/NUCLEO_F7x6ZG/variant.h
Labels: New variant

#1018 Arduino cli fix
  CI/build/arduino-cli.py
  CI/build/conf/cores_config.json
  platform.txt
Labels: Enhancement, Fix

#997 Refactor USB pullup handling
  cores/arduino/stm32/usb/usbd_if.c
  variants/Generic_F401Rx/variant.h
  variants/MALYANM200_F103CB/variant.cpp
  variants/MALYANM200_F103CB/variant.h
  variants/MAPLEMINI_F103CB/variant.h
  variants/board_template/variant.h
Labels: Enhancement

#1013 Add new Thunderpack v1.1: STM32F411
  CI/build/conf/cores_config.json
  README.md
  boards.txt
  variants/THUNDERPACK/PeripheralPins.c
  variants/THUNDERPACK/PinNamesVar.h
  variants/THUNDERPACK/README.md
  variants/THUNDERPACK/ldscript.ld
  variants/THUNDERPACK/variant.cpp
  variants/THUNDERPACK/variant.h
  variants/THUNDER_PACK/PeripheralPins.c
  variants/THUNDER_PACK/ldscript.ld
Labels: New variant

#1017 Rename PILL_C8 boards definition to PILL_CB
  CI/build/conf/cores_config.json
  CI/build/conf/cores_config_ci.json
  CI/build/conf/cores_config_travis.json
  boards.txt
  variants/PILL_F103XX/variant.h
Labels: Enhancement

#1019 F4x1 re update
  boards.txt
  variants/NUCLEO_F401RE/PeripheralPins.c
  variants/NUCLEO_F401RE/ldscript.ld
  variants/NUCLEO_F401RE/variant.cpp
  variants/NUCLEO_F411RE/PinNamesVar.h
  variants/NUCLEO_F411RE/ldscript.ld
  variants/NUCLEO_F411RE/variant.h
  variants/NUCLEO_F4x1RE/PeripheralPins.c
  variants/NUCLEO_F4x1RE/PinNamesVar.h
  variants/NUCLEO_F4x1RE/ldscript.ld
  variants/NUCLEO_F4x1RE/variant.cpp
  variants/NUCLEO_F4x1RE/variant.h
Labels: Enhancement

#1021 Force LF line endings
  .editorconfig
  .gitattributes
  CI/astyle/.astylerc
Labels: Enhancement
