Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2020-12, with the labels that each got.

#1246 [HardwareTimer] Fix typo
  cores/arduino/HardwareTimer.cpp
Labels: Bug, Fix

#1242 Fix two assert_param calls.
  libraries/Wire/src/utility/twi.c
Labels: Bug, Fix

#1247 HardwareTimer: Fix assert failed when using TIMER_OUTPUT_COMPARE
  cores/arduino/HardwareTimer.cpp
  cores/arduino/HardwareTimer.h
  cores/arduino/Tone.cpp
  libraries/Servo/src/stm32/Servo.cpp
Labels: Bug, Fix

#1255 [U(S)ART] hardening
  cores/arduino/HardwareSerial.cpp
  cores/arduino/HardwareSerial.h
  cores/arduino/WSerial.cpp
  cores/arduino/WSerial.h
  keywords.txt
  libraries/SrcWrapper/src/stm32/uart.c
Labels: Enhancement, Fix

#1257 Add I2S and SAI support in the HAL conf
  cores/arduino/stm32/stm32yyxx_hal_conf.h
Labels: New feature

#1268 dtostrf should not print fractional part if prec is 0
  cores/arduino/avr/dtostrf.c
Labels: Enhancement, Fix
