Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2020-08, with the labels that each got.

#1131 Fix flash offset on HY_TinySTM103T variant.
  variants/HY_TinySTM103T/ldscript.ld
Labels: Enhancement, Fix

#1117 Moved from arm-none-eabi-gcc 9.2.1-1.1 to 9.3.1-1.1
  .github/workflows/Continuous-Integration.yml
  platform.txt
Labels: Enhancement

#1141 [G0] Fix Timer and USART IRQ definition
  cores/arduino/stm32/timer.h
  cores/arduino/stm32/uart.h
Labels: Fix

#1148 Update STM32F3 HAL driver
  system/Drivers/STM32F3xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h
  system/Drivers/STM32F3xx_HAL_Driver/Inc/stm32f3xx_hal_i2c.h
  system/Drivers/STM32F3xx_HAL_Driver/Inc/stm32f3xx_hal_i2c_ex.h
  system/Drivers/STM32F3xx_HAL_Driver/Inc/stm32f3xx_hal_pcd.h
  system/Drivers/STM32F3xx_HAL_Driver/Inc/stm32f3xx_hal_pcd_ex.h
  system/Drivers/STM32F3xx_HAL_Driver/Inc/stm32f3xx_hal_smbus.h
  system/Drivers/STM32F3xx_HAL_Driver/Inc/stm32f3xx_ll_gpio.h
  system/Drivers/STM32F3xx_HAL_Driver/Inc/stm32f3xx_ll_i2c.h
  system/Drivers/STM32F3xx_HAL_Driver/Inc/stm32f3xx_ll_usb.h
  system/Drivers/STM32F3xx_HAL_Driver/License.md
  system/Drivers/STM32F3xx_HAL_Driver/README.md
  system/Drivers/STM32F3xx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.c
  system/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.c
  system/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.c
  system/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.c
  system/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.c
  system/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.c
  system/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_smbus.c
  system/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_ll_gpio.c
  system/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_ll_usb.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement

#1150 Update STM32F0 HAL driver
  system/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h
  system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_hal_def.h
  system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_hal_i2c.h
  system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_hal_i2c_ex.h
  system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_hal_pcd.h
  system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_hal_pcd_ex.h
  system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_hal_smbus.h
  system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_ll_gpio.h
  system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_ll_i2c.h
  system/Drivers/STM32F0xx_HAL_Driver/Inc/stm32f0xx_ll_usb.h
  system/Drivers/STM32F0xx_HAL_Driver/License.md
  system/Drivers/STM32F0xx_HAL_Driver/README.md
  system/Drivers/STM32F0xx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal.c
  system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_gpio.c
  system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c.c
  system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c_ex.c
  system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd.c
  system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd_ex.c
  system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smbus.c
  system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_gpio.c
  system/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_usb.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement

#1129 [WIP] stm32L0xx soc series has an embedded EEPROM
  cores/arduino/stm32/stm32_eeprom.h
  libraries/SrcWrapper/src/stm32/stm32_eeprom.c
Labels: Fix

#1152 Move the STM32 eeprom driver from core to library
  cores/arduino/board.h
  libraries/EEPROM/src/EEPROM.h
  libraries/EEPROM/src/utility/stm32_eeprom.c
  libraries/EEPROM/src/utility/stm32_eeprom.h
Labels: Enhancement

#1159 Update STM32F1 HAL drivers
  CI/utils/patch/HAL/F1/0001-F1-I2C-HAL-fix-generate-Start-only-once-Stop-is-fini.patch
  system/Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal.h
  system/Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_hcd.h
  system/Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_i2c.h
  system/Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_pcd.h
  system/Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_pcd_ex.h
  system/Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_ll_i2c.h
  system/Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_ll_usb.h
  system/Drivers/STM32F1xx_HAL_Driver/License.md
  system/Drivers/STM32F1xx_HAL_Driver/README.md
  system/Drivers/STM32F1xx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c
  system/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_hcd.c
  system/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2c.c
  system/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd.c
  system/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd_ex.c
  system/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_timebase_rtc_alarm_template.c
  system/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_timebase_tim_template.c
  system/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement
