Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2020-05, with the labels that each got.

#1044 Improve supported boards list
  README.md
Labels: Enhancement

#1054 Added STM32F072CB varant for the Elektor LoRa Node
  boards.txt
  variants/ELEKTOR_F072Cx/PeripheralPins.c
  variants/ELEKTOR_F072Cx/PinNamesVar.h
  variants/ELEKTOR_F072Cx/ldscript.ld
  variants/ELEKTOR_F072Cx/variant.cpp
  variants/ELEKTOR_F072Cx/variant.h
Labels: New variant

#1053 Added variant NUCLEO-F072RB
  boards.txt
  variants/NUCLEO_F072RB/PeripheralPins.c
  variants/NUCLEO_F072RB/PinNamesVar.h
  variants/NUCLEO_F072RB/ldscript.ld
  variants/NUCLEO_F072RB/variant.cpp
  variants/NUCLEO_F072RB/variant.h
Labels: New variant

#1055 HardwareTimer: Fix resume after pause issue introduced with G4 Cube update
  cores/arduino/HardwareTimer.cpp
Labels: Fix

#1056 HardwareTimer: fix servo regression introduced by ARR preload enabled
  libraries/Servo/src/stm32/Servo.cpp
Labels: Fix

#1058 Update to latest STM32CubeL4
  system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/stm32l4p5xx.h
  system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/stm32l4q5xx.h
  system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/stm32l4r5xx.h
  system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/stm32l4r7xx.h
  system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/stm32l4r9xx.h
  system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/stm32l4s5xx.h
  system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/stm32l4s7xx.h
  system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/stm32l4s9xx.h
  system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/stm32l4xx.h
  system/Drivers/CMSIS/Device/ST/STM32L4xx/Release_Notes.html
  system/Drivers/CMSIS/Device/ST/STM32YYxx_CMSIS_version.md
  system/Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_cortex.h
  system/Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_rtc_ex.h
  system/Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_smbus.h
  system/Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_ll_cortex.h
  system/Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_ll_utils.h
  system/Drivers/STM32L4xx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c
  system/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c
  system/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c
  system/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.c
  system/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_mmc.c
  system/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_sd.c
  system/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_smbus.c
  system/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_utils.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement

#1059 Update to latest STM32CubeF2
  system/Drivers/CMSIS/Device/ST/STM32F2xx/Include/generate.bat
  system/Drivers/CMSIS/Device/ST/STM32F2xx/Include/stm32f2xx.h
  system/Drivers/CMSIS/Device/ST/STM32F2xx/Release_Notes.html
  system/Drivers/CMSIS/Device/ST/STM32F2xx/_htmresc/mini-st.css
  system/Drivers/CMSIS/Device/ST/STM32F2xx/_htmresc/st_logo.png
  system/Drivers/CMSIS/Device/ST/STM32YYxx_CMSIS_version.md
  system/Drivers/STM32F2xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h
  system/Drivers/STM32F2xx_HAL_Driver/Inc/stm32f2xx_hal_i2c.h
  system/Drivers/STM32F2xx_HAL_Driver/Inc/stm32f2xx_hal_irda.h
  system/Drivers/STM32F2xx_HAL_Driver/Inc/stm32f2xx_hal_smartcard.h
  system/Drivers/STM32F2xx_HAL_Driver/Inc/stm32f2xx_hal_uart.h
  system/Drivers/STM32F2xx_HAL_Driver/Inc/stm32f2xx_hal_usart.h
  system/Drivers/STM32F2xx_HAL_Driver/Inc/stm32f2xx_ll_usart.h
  system/Drivers/STM32F2xx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32F2xx_HAL_Driver/Src/stm32f2xx_hal.c
  system/Drivers/STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_adc_ex.c
  system/Drivers/STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_gpio.c
  system/Drivers/STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_i2c.c
  system/Drivers/STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_irda.c
  system/Drivers/STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_smartcard.c
  system/Drivers/STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_uart.c
  system/Drivers/STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_usart.c
  system/Drivers/STM32F2xx_HAL_Driver/Src/stm32f2xx_ll_adc.c
  system/Drivers/STM32F2xx_HAL_Driver/Src/stm32f2xx_ll_gpio.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement

#1062 Fixed setting HardwareTimer interrupt priority
  cores/arduino/HardwareTimer.cpp
Labels: Enhancement

#1067 Add NadHAT PYBSTICK26 variants
  README.md
  boards.txt
  variants/PYBSTICK26_DUINO/PeripheralPins.c
  variants/PYBSTICK26_DUINO/PinNamesVar.h
  variants/PYBSTICK26_DUINO/ldscript.ld
  variants/PYBSTICK26_DUINO/variant.cpp
  variants/PYBSTICK26_DUINO/variant.h
  variants/PYBSTICK26_LITE/PeripheralPins.c
  variants/PYBSTICK26_LITE/PinNamesVar.h
  variants/PYBSTICK26_LITE/ldscript.ld
  variants/PYBSTICK26_LITE/variant.cpp
  variants/PYBSTICK26_LITE/variant.h
  variants/PYBSTICK26_PRO/PeripheralPins.c
  variants/PYBSTICK26_PRO/PinNamesVar.h
  variants/PYBSTICK26_PRO/ldscript.ld
  variants/PYBSTICK26_PRO/variant.cpp
  variants/PYBSTICK26_PRO/variant.h
  variants/PYBSTICK26_STD/PeripheralPins.c
  variants/PYBSTICK26_STD/PinNamesVar.h
  variants/PYBSTICK26_STD/ldscript.ld
  variants/PYBSTICK26_STD/variant.cpp
  variants/PYBSTICK26_STD/variant.h
Labels: New variant

#1068 [PYBStick] Add Sx pin number naming Eg. S3 (pin 3) = D0 (arduino) = PB9 (stm32 mcu)
  variants/PYBSTICK26_DUINO/variant.h
  variants/PYBSTICK26_LITE/variant.h
  variants/PYBSTICK26_PRO/variant.h
  variants/PYBSTICK26_STD/variant.h
Labels: Enhancement

#1070 Add Daisy Seed variant [replace #1063]
  CI/build/conf/cores_config.json
  CI/build/conf/cores_config_ci.json
  README.md
  boards.txt
  variants/DAISY_SEED/PeripheralPins.c
  variants/DAISY_SEED/PinNamesVar.h
  variants/DAISY_SEED/ldscript.ld
  variants/DAISY_SEED/variant.cpp
  variants/DAISY_SEED/variant.h
Labels: New variant

#1084 Add support of B-L4S5I-IOT01A variant
  README.md
  boards.txt
  variants/B_L4S5I_IOT01A/PeripheralPins.c
  variants/B_L4S5I_IOT01A/PinNamesVar.h
  variants/B_L4S5I_IOT01A/ldscript.ld
  variants/B_L4S5I_IOT01A/variant.cpp
  variants/B_L4S5I_IOT01A/variant.h
Labels: New variant
