Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2020-01, with the labels that each got.

#847 Add missing ADC clock config for Generic F103xE
  variants/Generic_F103Rx/variant.cpp
Labels: Enhancement

#853 I2C: allow static redefinition of I2C buffer size
  libraries/Wire/src/utility/twi.h
Labels: Enhancement

#856 Add generic F411Rx variant
  boards.txt
  variants/Generic_F411Rx/PeripheralPins.c
  variants/Generic_F411Rx/PinNamesVar.h
  variants/Generic_F411Rx/ldscript.ld
  variants/Generic_F411Rx/variant.cpp
  variants/Generic_F411Rx/variant.h
Labels: New variant

#852 HardwareTimer: Clear IT flag only if callback not previously configured
  cores/arduino/HardwareTimer.cpp
Labels: Enhancement

#867 Print::printf() generic
  cores/arduino/Print.cpp
Labels: Enhancement

#872 [I2C] Fix error reporting on I2C timeout
  libraries/Wire/src/utility/twi.c
Labels: Fix

#866 Add generic F411Cx pinout
  boards.txt
  variants/Generic_F411Cx/PeripheralPins.c
  variants/Generic_F411Cx/PinNamesVar.h
  variants/Generic_F411Cx/ldscript.ld
  variants/Generic_F411Cx/variant.cpp
  variants/Generic_F411Cx/variant.h
Labels: New variant

#882 Fix TIM1_IRQn definition when TIM10 is not defined
  cores/arduino/stm32/timer.h
Labels: Fix

#884 [CDC]: Do not claim AT-protocol in CDC interface descriptor
  cores/arduino/stm32/usb/cdc/usbd_cdc.c
Labels: Enhancement

#889 Servo: enlarge pin number range to [0..255]
  libraries/Servo/src/Servo.h
Labels: Fix

#893 [HardwareSerial] Fix ambiguous call of overloaded function
  cores/arduino/HardwareSerial.cpp
  cores/arduino/HardwareSerial.h
  keywords.txt
Labels: Fix

#883 I2C wait end of stop before start
  system/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2c.c
  system/Drivers/STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_i2c.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c
  system/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_i2c.c
Labels: Fix

#851 F103Zx support
  README.md
  boards.txt
  variants/Generic_F103Zx/PeripheralPins.c
  variants/Generic_F103Zx/PinNamesVar.h
  variants/Generic_F103Zx/ldscript.ld
  variants/Generic_F103Zx/variant.cpp
  variants/Generic_F103Zx/variant.h
Labels: New variant

#901 [IWatchdog library] Add license
  libraries/IWatchdog/src/IWatchdog.cpp
  libraries/IWatchdog/src/IWatchdog.h
Labels: Fix

#887 USB-related improvements
  boards.txt
  cores/arduino/stm32/usb/usbd_desc.c
  platform.txt
Labels: Enhancement

#902 HardwareTimer: Fix ARR and CCRx computation
  cores/arduino/HardwareTimer.cpp
Labels: Fix

#900 HardwareTimer: Allow setting preload enable bits
  cores/arduino/HardwareTimer.cpp
  cores/arduino/HardwareTimer.h
Labels: Enhancement

#888 I2C multi instances: Remove static qualifier on TwoWire attributes
  libraries/Wire/src/Wire.cpp
  libraries/Wire/src/Wire.h
  libraries/Wire/src/utility/twi.c
  libraries/Wire/src/utility/twi.h
Labels: Fix

#874 Add generic F401Cx pinout
  boards.txt
  variants/Generic_F401Cx/PeripheralPins.c
  variants/Generic_F401Cx/PinNamesVar.h
  variants/Generic_F401Cx/ldscript.ld
  variants/Generic_F401Cx/variant.cpp
  variants/Generic_F401Cx/variant.h
Labels: New variant

#880 Add generic F410Rx pinout
  boards.txt
  variants/Generic_F410Rx/PeripheralPins.c
  variants/Generic_F410Rx/PinNamesVar.h
  variants/Generic_F410Rx/ldscript.ld
  variants/Generic_F410Rx/variant.cpp
  variants/Generic_F410Rx/variant.h
Labels: New variant
