Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2020-04, with the labels that each got.

#1026 Script to update HAL drivers and CMSIS devices from the STM32Cube GitHub release
  .gitattributes
  .gitignore
  CI/utils/patch/CMSIS/MP1/0001-MP1-Review-HAL-default-configuration.patch
  CI/utils/patch/HAL/F1/0001-F1-I2C-HAL-fix-generate-Start-only-once-Stop-is-fini.patch
  CI/utils/patch/HAL/F2/0001-F2-I2C-HAL-fix-generate-Start-only-once-Stop-is-fini.patch
  CI/utils/patch/HAL/F4/0001-F4-Fix-HAL_RCC_USART3-definition-for-STM32F412Cx.patch
  CI/utils/patch/HAL/F4/0001-F4-I2C-HAL-fix-generate-Start-only-once-Stop-is-fini.patch
  CI/utils/patch/HAL/G0/0001-G0-Fix-HAL-definition.patch
  CI/utils/patch/HAL/G4/0001-G4-Fix-LL-FMC-build-issue-introduce-in-HAL-version-v.patch
  CI/utils/patch/HAL/L1/0001-L1-I2C-HAL-fix-generate-Start-only-once-Stop-is-fini.patch
  CI/utils/stm32common.py
  CI/utils/stm32update.py
  CI/utils/stm32wrapper.py
Labels: Enhancement

#1030 Unified some Generic variant definition and update CI configuration
  CI/build/arduino-cli.py
  CI/build/conf/cores_config.json
  CI/build/conf/cores_config_ci.json
  README.md
  boards.txt
  variants/BLACK_F407XX/variant.h
  variants/Generic_F103Rx/variant.cpp
  variants/Generic_F103Rx/variant.h
  variants/Generic_F103Zx/variant.h
  variants/Generic_F411Cx/variant.h
  variants/Generic_F4x5RG/variant.h
Labels: Enhancement

#1032 Add more Generic_F103Rx targets
  README.md
  boards.txt
  variants/Generic_F103Rx/PeripheralPins.c
  variants/Generic_F103Rx/variant.h
Labels: New variant

#1037 Add generic F103Cx targets
  README.md
  boards.txt
  variants/Generic_F103Cx/PeripheralPins.c
  variants/Generic_F103Cx/PinNamesVar.h
  variants/Generic_F103Cx/ldscript.ld
  variants/Generic_F103Cx/variant.cpp
  variants/Generic_F103Cx/variant.h
Labels: New variant

#1040 Fix DAC for F103RF and RG
  variants/Generic_F103Rx/variant.h
Labels: Fix

#1039 HardwareTimer: specific F1 GPIO needs Alternate Function configuration
  cores/arduino/HardwareTimer.cpp
  libraries/SrcWrapper/src/stm32/pinmap.c
Labels: Fix

#1042 Add generic F103Vx targets
  README.md
  boards.txt
  variants/Generic_F103Vx/PeripheralPins.c
  variants/Generic_F103Vx/PinNamesVar.h
  variants/Generic_F103Vx/ldscript.ld
  variants/Generic_F103Vx/variant.cpp
  variants/Generic_F103Vx/variant.h
Labels: New variant

#1043 Add support for F103Tx chips
  README.md
  boards.txt
  variants/Generic_F103Tx/PeripheralPins.c
  variants/Generic_F103Tx/PinNamesVar.h
  variants/Generic_F103Tx/ldscript.ld
  variants/Generic_F103Tx/variant.cpp
  variants/Generic_F103Tx/variant.h
Labels: New variant

#1048 Fix external and internal usb pullup
  boards.txt
  cores/arduino/stm32/usb/usbd_if.c
  variants/BLACK_F407XX/variant.h
  variants/BLUE_F407VE_Mini/variant.h
  variants/Generic_F401Rx/variant.h
  variants/board_template/variant.h
Labels: Enhancement
