Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2020-02, with the labels that each got.

#904 Change clock setup for Generic F411's
  variants/Generic_F411Rx/variant.cpp
Labels: Enhancement, Fix

#905 Generic F4 series
  variants/Generic_F401Cx/variant.h
  variants/Generic_F401Rx/variant.cpp
  variants/Generic_F401Rx/variant.h
  variants/Generic_F410Rx/PeripheralPins.c
  variants/Generic_F410Rx/variant.h
  variants/Generic_F411Cx/variant.cpp
  variants/Generic_F411Cx/variant.h
  variants/Generic_F411Rx/variant.h
  variants/NUCLEO_F446RE/PeripheralPins.c
  variants/RUMBA32_F446VE/PeripheralPins.c
  variants/VAKE_F446VE/PeripheralPins.c
Labels: Enhancement

#877 Add generic F446Rx pinout
  boards.txt
  variants/Generic_F446Rx/PeripheralPins.c
  variants/Generic_F446Rx/PinNamesVar.h
  variants/Generic_F446Rx/ldscript.ld
  variants/Generic_F446Rx/variant.cpp
  variants/Generic_F446Rx/variant.h
Labels: New variant

#909 Use of Generic F4 variants to define specific boards
  boards.txt
  variants/CoreBoard_F401RC/PeripheralPins.c
  variants/CoreBoard_F401RC/PinNamesVar.h
  variants/CoreBoard_F401RC/ldscript.ld
  variants/CoreBoard_F401RC/variant.cpp
  variants/CoreBoard_F401RC/variant.h
  variants/Generic_F401Cx/PeripheralPins.c
  variants/Generic_F401Cx/ldscript.ld
  variants/Generic_F401Cx/variant.h
  variants/Generic_F401Rx/PeripheralPins.c
  variants/Generic_F401Rx/variant.h
  variants/Generic_F411Cx/PeripheralPins.c
  variants/Generic_F411Cx/variant.h
  variants/PILL_F401XX/PeripheralPins.c
  variants/PILL_F401XX/PinNamesVar.h
  variants/PILL_F401XX/ldscript.ld
  variants/PILL_F401XX/variant.cpp
  variants/PILL_F401XX/variant.h
Labels: Enhancement, New variant

#910 analogRead: don't set ADC common register when ADC doesn't support it.
  libraries/SrcWrapper/src/stm32/analog.cpp
Labels: Fix

#913 Add STM32G0316-DISCO
  README.md
  boards.txt
  libraries/SrcWrapper/src/stm32/pinmap.c
  variants/DISCO_G0316/PeripheralPins.c
  variants/DISCO_G0316/PinNamesVar.h
  variants/DISCO_G0316/ldscript.ld
  variants/DISCO_G0316/variant.cpp
  variants/DISCO_G0316/variant.h
Labels: Enhancement, New variant

#914 Add generic F410Cx pinout
  boards.txt
  variants/Generic_F410Cx/PeripheralPins.c
  variants/Generic_F410Cx/PinNamesVar.h
  variants/Generic_F410Cx/ldscript.ld
  variants/Generic_F410Cx/variant.cpp
  variants/Generic_F410Cx/variant.h
Labels: New variant

#915 Add genric F405Rx/F415Rx variant
  README.md
  boards.txt
  variants/Generic_F4x5RG/PeripheralPins.c
  variants/Generic_F4x5RG/PinNamesVar.h
  variants/Generic_F4x5RG/ldscript.ld
  variants/Generic_F4x5RG/variant.cpp
  variants/Generic_F4x5RG/variant.h
Labels: New variant

#918 Add support of NUCLEO_L433RC_P
  boards.txt
  variants/NUCLEO_L433RC_P/PeripheralPins.c
  variants/NUCLEO_L433RC_P/PinNamesVar.h
  variants/NUCLEO_L433RC_P/ldscript.ld
  variants/NUCLEO_L433RC_P/variant.cpp
  variants/NUCLEO_L433RC_P/variant.h
Labels: New variant

#920 Add generic F412Rx pinout variant
  README.md
  boards.txt
  variants/Generic_F412Rx/PeripheralPins.c
  variants/Generic_F412Rx/PinNamesVar.h
  variants/Generic_F412Rx/ldscript.ld
  variants/Generic_F412Rx/variant.cpp
  variants/Generic_F412Rx/variant.h
Labels: New variant

#922 Update variant.cpp
  variants/ELEKTOR_F072C8/variant.cpp
Labels: Fix

#921 Fix SPI mapping for some generic F4 variants
  variants/Generic_F401Cx/variant.h
  variants/Generic_F401Rx/PeripheralPins.c
  variants/Generic_F401Rx/variant.h
  variants/Generic_F410Cx/variant.h
  variants/Generic_F410Rx/variant.h
  variants/Generic_F411Cx/variant.h
  variants/Generic_F411Rx/PeripheralPins.c
  variants/Generic_F411Rx/variant.h
  variants/Generic_F446Rx/variant.h
Labels: Enhancement, Fix

#925 Add generic F413R/F423R pinout variant
  README.md
  boards.txt
  variants/Generic_F4x3Rx/PeripheralPins.c
  variants/Generic_F4x3Rx/PinNamesVar.h
  variants/Generic_F4x3Rx/ldscript.ld
  variants/Generic_F4x3Rx/variant.cpp
  variants/Generic_F4x3Rx/variant.h
Labels: New variant

#931 EEPROM hardfault: eeprom_buffer should be 8 bytes aligned
  libraries/SrcWrapper/src/stm32/stm32_eeprom.c
Labels: Fix

#928 Add generic F413C/F423C pinout variant
  README.md
  boards.txt
  variants/Generic_F4x3Cx/PeripheralPins.c
  variants/Generic_F4x3Cx/PinNamesVar.h
  variants/Generic_F4x3Cx/ldscript.ld
  variants/Generic_F4x3Cx/variant.cpp
  variants/Generic_F4x3Cx/variant.h
Labels: New variant

#912 SPI: improvements for SPI library
  libraries/SPI/src/SPI.cpp
  libraries/SPI/src/SPI.h
  libraries/SPI/src/utility/spi_com.c
  libraries/SPI/src/utility/spi_com.h
Labels: Enhancement

#937 Add generic F407Vx/F417Vx pinout variant
  README.md
  boards.txt
  variants/Generic_F4x7Vx/PeripheralPins.c
  variants/Generic_F4x7Vx/PinNamesVar.h
  variants/Generic_F4x7Vx/ldscript.ld
  variants/Generic_F4x7Vx/variant.cpp
  variants/Generic_F4x7Vx/variant.h
Labels: New variant

#938 EEPROM emulation: wrong flash sector used for some F7 variants
  variants/NUCLEO_F767ZI/variant.h
  variants/REMRAM_V1/variant.h
Labels: Enhancement, Fix

#941 Hardwaretimer analogWrite() no glitch
  cores/arduino/HardwareTimer.cpp
  cores/arduino/HardwareTimer.h
  libraries/SrcWrapper/src/stm32/analog.cpp
Labels: Enhancement

#940 Fix F4x7vx definitions
  boards.txt
  variants/BLACK_F407XX/variant.cpp
  variants/BLUE_F407VE_Mini/variant.cpp
  variants/DISCO_F407VG/ldscript.ld
  variants/DISCO_F407VG/variant.cpp
  variants/DIYMORE_F407VGT/variant.cpp
  variants/FEATHER_F405/variant.cpp
  variants/FK407M1/variant.cpp
  variants/Generic_F412Cx/ldscript.ld
  variants/Generic_F412Rx/ldscript.ld
  variants/Generic_F4x3Cx/ldscript.ld
  variants/Generic_F4x3Rx/ldscript.ld
  variants/Generic_F4x5RG/variant.cpp
  variants/Generic_F4x7Vx/ldscript.ld
  variants/Generic_F4x7Vx/variant.cpp
  variants/NUCLEO_F429ZI/variant.cpp
  variants/PRNTR_Vx/ldscript.ld
  variants/PRNTR_Vx/variant.cpp
Labels: Fix

#924 Add initial support for PlatformIO ecosystem
  .travis.yml
  CI/build/platformio-builder.py
  package.json
  tools/platformio-build.py
Labels: New feature

#945 [PIO] Apply black and flake8 on python scripts
  CI/build/platformio-builder.py
  tools/.flake8
  tools/platformio-build.py
Labels: Enhancement

#951 Update CI
  .github/workflows/Continuous-Integration.yml
Labels: Enhancement

#952 Add PlatformIO Test to the workflow
  .github/actions/pio-build/Dockerfile
  .github/actions/pio-build/README.md
  .github/actions/pio-build/action.yml
  .github/actions/pio-build/entrypoint.sh
  .github/workflows/Continuous-Integration.yml
  CI/build/platformio-builder.py
Labels: Enhancement

#953 Wire: rxBuffer should be initialized before using it
  libraries/Wire/src/Wire.cpp
Labels: Fix

#955 [CI] Follow best practices in action scripts
  .github/actions/pio-build/Dockerfile
  .github/actions/pio-build/entrypoint.sh
Labels: Enhancement
