Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2021-06, with the labels that each got.

#1407 Dual pad analog switch: skip gpio configuration in case of direct ADC
  libraries/SrcWrapper/src/stm32/pinmap.c
Labels: Enhancement, Fix

#1417 Update variant_BLACK_F407ZX.cpp
  variants/STM32F4xx/F407Z(E-G)T_F417Z(E-G)T/variant_BLACK_F407ZX.cpp
Labels: Fix

#1423 Discovery board B_G431B_ESC1 - Uncomment PA_10 to allow timer for A_PHASE_WH
  variants/STM32G4xx/G431C(6-8-B)U_G441CBU/PeripheralPins_DISCO_B_G431B_ESC1.c
Labels: Fix

#1414 Support for elecgator EtherCATduino board
  README.md
  boards.txt
  variants/STM32F7xx/F745Z(E-G)T_F746Z(E-G)(T-Y)_F750Z8T_F756ZG(T-Y)/PeripheralPins_ETHERCAT_DUINO.c
  variants/STM32F7xx/F745Z(E-G)T_F746Z(E-G)(T-Y)_F750Z8T_F756ZG(T-Y)/variant_ETHERCAT_DUINO.cpp
  variants/STM32F7xx/F745Z(E-G)T_F746Z(E-G)(T-Y)_F750Z8T_F756ZG(T-Y)/variant_ETHERCAT_DUINO.h
Labels: New variant

#1431 HardwareTimer: update function header and parameter description
  cores/arduino/HardwareTimer.cpp
Labels: Documentation :books:, Fix

#1435 core: backup: use register definition instead of serie name
  cores/arduino/stm32/backup.h
Labels: Enhancement
