Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2021-01, with the labels that each got.

#1269 SoftwareSerial stopListening at the begining
  libraries/SoftwareSerial/src/SoftwareSerial.cpp
Labels: Fix

#1281 Prevent redefine of HSE_VALUE if already user-overridden
  variants/Generic_F401Cx/variant.h
  variants/Generic_F411Cx/variant.h
Labels: Enhancement

#1282 Wire: change definition of MASTER_ADDRESS to avoid potential conflict
  libraries/Wire/src/Wire.cpp
  libraries/Wire/src/Wire.h
Labels: Arduino compatibility, Fix

#1274 Add bootloader support for PRNTRBoard V2.
  boards.txt
  variants/PRNTR_Vx/ldscript.ld
Labels: Enhancement, New feature

#1265 Daisy Seed - added missing ram section to linker
  variants/DAISY_SEED/ldscript.ld
Labels: Enhancement

#1287 fix: wrong timer source for frequency calculation with STM32G0xx controllers
  libraries/SrcWrapper/src/stm32/timer.c
Labels: Fix
