Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2021-09, with the labels that each got.

#1486 library: enhance peripheral clock frequency management
  libraries/SPI/src/utility/spi_com.c
  libraries/Wire/src/utility/twi.c
Labels: Enhancement

#1488 library: spi: enhancement
  libraries/SPI/src/utility/spi_com.c
Labels: Enhancement, Fix

#1489 chore: update SPI pins for Swan_R5
  variants/STM32L4xx/L4R5Z(G-I)Y_L4R9Z(G-I)Y_L4S5ZIY_L4S9ZIY/variant_SWAN_R5.h
Labels: Enhancement

#1493 bsp: ADC enhancements
  libraries/SrcWrapper/src/stm32/analog.cpp
Labels: Enhancement, Fix

#1494 Configure Swan R5 initial behaviors
  variants/STM32L4xx/L4R5Z(G-I)Y_L4R9Z(G-I)Y_L4S5ZIY_L4S9ZIY/PeripheralPins_SWAN_R5.c
  variants/STM32L4xx/L4R5Z(G-I)Y_L4R9Z(G-I)Y_L4S5ZIY_L4S9ZIY/variant_SWAN_R5.cpp
  variants/STM32L4xx/L4R5Z(G-I)Y_L4R9Z(G-I)Y_L4S5ZIY_L4S9ZIY/variant_SWAN_R5.h
Labels: Enhancement

#1506 spi: Add delay before disabling SPI to avoid truncated clock/data signals
  libraries/SPI/src/utility/spi_com.c
  libraries/SPI/src/utility/spi_com.h
Labels: Fix

#1507 fix(usart): enable peripheral bus clock when SRD domain is in DRUN
  libraries/SrcWrapper/src/stm32/uart.c
Labels: Enhancement, Fix

#1511 Move Swan board to dedicated menu and add a workaround for SWD upload method
  README.md
  boards.txt
Labels: Fix
