Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2021-03, with the labels that each got.

#1320 Wire examples: rename old *.pde files to *.ino
  libraries/Wire/examples/SFRRanger_reader/SFRRanger_reader.ino
  libraries/Wire/examples/digital_potentiometer/digital_potentiometer.ino
  libraries/Wire/examples/master_reader/master_reader.ino
  libraries/Wire/examples/master_writer/master_writer.ino
  libraries/Wire/examples/slave_receiver/slave_receiver.ino
  libraries/Wire/examples/slave_sender/slave_sender.ino
Labels: Fix

#1310 Fix HAL not properly initialized on F105x series
  system/Drivers/CMSIS/Device/ST/STM32F1xx/Source/Templates/gcc/startup_stm32f105xc.s
Labels: Fix

#1313 HardwareSerial: don't call STM32 HAL for every bytes to transfer
  cores/arduino/HardwareSerial.cpp
  cores/arduino/HardwareSerial.h
  cores/arduino/stm32/uart.h
  libraries/SrcWrapper/src/stm32/uart.c
Labels: Enhancement

#1321 Review HAL/LL default configuration
  boards.txt
  cores/arduino/stm32/stm32yyxx_hal_conf.h
  libraries/SrcWrapper/src/stm32/PortNames.c
  libraries/SrcWrapper/src/stm32/pinmap.c
  platform.txt
Labels: Enhancement

#1326 DAC fixes
  libraries/SrcWrapper/src/stm32/analog.cpp
Labels: Fix

#1340 Update STM32MP1 HAL and CMSIS drivers
  CI/utils/patch/CMSIS/MP1/0001-MP1-Review-HAL-default-configuration.patch
  cores/arduino/stm32/stm32_def_build.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp151axx_ca7.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp151axx_cm4.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp151cxx_ca7.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp151cxx_cm4.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp151dxx_ca7.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp151dxx_cm4.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp151fxx_ca7.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp151fxx_cm4.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp153axx_ca7.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp153axx_cm4.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp153cxx_ca7.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp153cxx_cm4.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp153dxx_ca7.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp153dxx_cm4.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp153fxx_ca7.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp153fxx_cm4.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp157axx_ca7.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp157axx_cm4.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp157cxx_ca7.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp157cxx_cm4.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp157dxx_ca7.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp157dxx_cm4.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp157fxx_ca7.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp157fxx_cm4.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Include/stm32mp1xx.h
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Release_Notes.html
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Source/Templates/gcc/startup_stm32mp151axx_cm4 .s
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Source/Templates/gcc/startup_stm32mp151cxx_cm4.s
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Source/Templates/gcc/startup_stm32mp153axx_cm4.s
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Source/Templates/gcc/startup_stm32mp153cxx_cm4.s
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Source/Templates/gcc/startup_stm32mp157axx_cm4.s
  system/Drivers/CMSIS/Device/ST/STM32MP1xx/Source/Templates/gcc/startup_stm32mp157cxx_cm4.s
  system/Drivers/CMSIS/Device/ST/STM32YYxx_CMSIS_version.md
  system/Drivers/STM32MP1xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h
  system/Drivers/STM32MP1xx_HAL_Driver/Inc/stm32mp1xx_hal_exti.h
  system/Drivers/STM32MP1xx_HAL_Driver/Inc/stm32mp1xx_hal_smartcard.h
  system/Drivers/STM32MP1xx_HAL_Driver/Inc/stm32mp1xx_hal_smartcard_ex.h
  system/Drivers/STM32MP1xx_HAL_Driver/Inc/stm32mp1xx_hal_usart.h
  system/Drivers/STM32MP1xx_HAL_Driver/Inc/stm32mp1xx_hal_usart_ex.h
  system/Drivers/STM32MP1xx_HAL_Driver/Inc/stm32mp1xx_ll_bus.h
  system/Drivers/STM32MP1xx_HAL_Driver/Inc/stm32mp1xx_ll_usart.h
  system/Drivers/STM32MP1xx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal.c
  system/Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_exti.c
  system/Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_smartcard.c
  system/Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_smartcard_ex.c
  system/Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_usart.c
  system/Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_usart_ex.c
  system/Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_ll_usart.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement, Fix
