Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2021-02, with the labels that each got.

#1291 WB enhancements
  cores/arduino/board.h
  cores/arduino/stm32/clock.h
  cores/arduino/stm32/lock_resource.h
  cores/arduino/stm32/otp.h
  cores/arduino/stm32/pinconfig.h
  cores/arduino/stm32/stm32yyxx_hal_conf.h
  libraries/SrcWrapper/src/stm32/analog.cpp
  libraries/SrcWrapper/src/stm32/clock.c
  libraries/SrcWrapper/src/stm32/hw_config.c
  libraries/SrcWrapper/src/stm32/interrupt.cpp
  libraries/SrcWrapper/src/stm32/lock_resource.c
  libraries/SrcWrapper/src/stm32/otp.c
  libraries/SrcWrapper/src/stm32/pinmap.c
  libraries/SrcWrapper/src/stm32/uart.c
  system/STM32MP1xx/stm32mp1xx_hal_conf_default.h
  variants/MKR_SHARKY/variant.h
  variants/PNUCLEO_WB55RG/otp.h
  variants/PNUCLEO_WB55RG/variant.cpp
Labels: Enhancement, Fix

#1298 [USB] Manage internal pull-up
  cores/arduino/stm32/usb/usbd_if.c
Labels: Fix

#1293 Adc channel bank support
  cores/arduino/stm32/PinNamesTypes.h
  libraries/SrcWrapper/src/stm32/analog.cpp
Labels: Enhancement, Fix

#1304 servo: optional default servo angle on attach
  libraries/Servo/src/Servo.h
  libraries/Servo/src/stm32/Servo.cpp
Labels: Enhancement
