Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2021-08, with the labels that each got.

#1466 variants: L1: update generated files to STM32_open_pin_data v6.0.30
  variants/STM32L1xx/L100C6Ux(A)_L151C(6-8-B)(T-U)x(A)_L152C(6-8-B)(T-U)x(A)/PeripheralPins.c
  variants/STM32L1xx/L100R(8-B)Tx(A)_L151R(6-8-B)Tx(A)_L152R(6-8-B)Tx(A)/PeripheralPins.c
  variants/STM32L1xx/L100RCT/PeripheralPins.c
  variants/STM32L1xx/L151CC(T-U)_L152CC(T-U)/PeripheralPins.c
  variants/STM32L1xx/L151QCH_L152QCH_L162QCH/PeripheralPins.c
  variants/STM32L1xx/L151QDH_L152QDH_L162QDH/PeripheralPins.c
  variants/STM32L1xx/L151QEH_L152QEH/PeripheralPins.c
  variants/STM32L1xx/L151R(6-8-B)Hx(A)_L152R(6-8-B)Hx(A)/PeripheralPins.c
  variants/STM32L1xx/L151RC(T-Y)x(A)_L151UCY_L152RCTx(A)_L152UCY_L162RCTx(A)/PeripheralPins.c
  variants/STM32L1xx/L151RD(T-Y)_L152RD(T-Y)_L162RD(T-Y)/PeripheralPins.c
  variants/STM32L1xx/L151RET_L152RET_L162RET/PeripheralPins.c
  variants/STM32L1xx/L151V(8-B)(H-T)x(A)_L152V(8-B)(H-T)x(A)/PeripheralPins.c
  variants/STM32L1xx/L151VC(H-T)x(A)_L152VC(H-T)x(A)_L162VC(H-T)x(A)/PeripheralPins.c
  variants/STM32L1xx/L151VD(T-Y)xX_L151VE(T-Y)_L152VDTxX_L152VE(T-Y)_L162VDYxX_L162VE(T-Y)/PeripheralPins.c
  variants/STM32L1xx/L151VDT_L152VDT_L162VDT/PeripheralPins.c
  variants/STM32L1xx/L151ZCT_L152ZCT_L162ZCT/PeripheralPins.c
  variants/STM32L1xx/L151ZDT_L152ZDT_L162ZDT/PeripheralPins.c
  variants/STM32L1xx/L151ZET_L152ZET_L162ZET/PeripheralPins.c
Labels: Fix

#1474 exclude fpu options from stm32wl55
  tools/platformio/platformio-build.py
Labels: Enhancement

#1482 Fix `bitWrite` with parenthesis
  cores/arduino/wiring_constants.h
Labels: Enhancement, Fix

#1485 variant: L4: add generic L433C(B-C)(T-U) and L443CC(T-U)
  README.md
  boards.txt
  variants/STM32L4xx/L433C(B-C)(T-U)_L443CC(T-U)/generic_clock.c
  variants/STM32L4xx/L433C(B-C)(T-U)_L443CC(T-U)/ldscript.ld
Labels: New variant
