Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2021-05, with the labels that each got.

#1379 fix: analog: use MAX_PWM_RESOLUTION instead of MAX_ADC_RESOLUTION
  cores/arduino/wiring_analog.c
Labels: Fix

#1375 Adding STORM32_V1_31_RC variant
  README.md
  boards.txt
  variants/STM32F1xx/F103R(C-D-E)T/PeripheralPins_STORM32_V1_31_RC.c
  variants/STM32F1xx/F103R(C-D-E)T/readme_STORM32_V1_31_RC.txt
  variants/STM32F1xx/F103R(C-D-E)T/variant_STORM32_V1_31_RC.cpp
  variants/STM32F1xx/F103R(C-D-E)T/variant_STORM32_V1_31_RC.h
Labels: New variant

#1383 variant NUCLEO_H743ZI: fix digitalPin typo
  variants/STM32H7xx/H742Z(G-I)T_H743Z(G-I)T_H747A(G-I)I_H747I(G-I)T_H750ZBT_H753ZIT_H757AII_H757IIT/variant_NUCLEO_H743ZI.cpp
Labels: Bug

#1382 USB CDC line state
  cores/arduino/USBSerial.cpp
  cores/arduino/USBSerial.h
  cores/arduino/stm32/usb/cdc/usbd_cdc.c
  cores/arduino/stm32/usb/cdc/usbd_cdc.h
  cores/arduino/stm32/usb/cdc/usbd_cdc_if.c
  cores/arduino/stm32/usb/cdc/usbd_cdc_if.h
Labels: Enhancement

#1384 variant: add Nucleo L010RB
  README.md
  boards.txt
  variants/STM32L0xx/L010RBT/variant_NUCLEO_L010RB.cpp
  variants/STM32L0xx/L010RBT/variant_NUCLEO_L010RB.h
Labels: New variant

#1393 fix: generic H7: clock configuration
  libraries/SPI/src/utility/spi_com.c
  variants/STM32H7xx/H742V(G-I)(H-T)_H743V(G-I)(H-T)_H750VBT_H753VI(H-T)/generic_clock.c
  variants/STM32H7xx/H742Z(G-I)T_H743Z(G-I)T_H747A(G-I)I_H747I(G-I)T_H750ZBT_H753ZIT_H757AII_H757IIT/generic_clock.c
  variants/STM32H7xx/H742Z(G-I)T_H743Z(G-I)T_H747A(G-I)I_H747I(G-I)T_H750ZBT_H753ZIT_H757AII_H757IIT/variant_NUCLEO_H743ZI.cpp
  variants/STM32H7xx/H743I(G-I)(K-T)_H750IBK_H753II(K-T)/generic_clock.c
Labels: Bug

#1403 Synchronize PlatformIO build script
  .github/actions/pio-build/entrypoint.sh
  tools/platformio/boards_remap.json
  tools/platformio/platformio-build.py
Labels: Fix
