Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2021-11, with the labels that each got.

#1540 fix(F2): Ethernet peripheral configuration for LAN8742A
  system/STM32F2xx/stm32f2xx_hal_conf_default.h
Labels: Fix

#1534 HardwareTimer: Allow delaying initialization to setup method
  cores/arduino/HardwareTimer.cpp
  cores/arduino/HardwareTimer.h
Labels: Enhancement

#1547 Feature/G030CxT
  README.md
  boards.txt
  variants/STM32G0xx/G030C(6-8)T/generic_clock.c
  variants/STM32G0xx/G030C(6-8)T/ldscript.ld
Labels: New variant

#1550 HardwareTimer: Add API to check whether timer/channels are running
  cores/arduino/HardwareTimer.cpp
  cores/arduino/HardwareTimer.h
Labels: Enhancement

#1553 Fix typos in variants/ subdirectory
  variants/STM32F0xx/F070CBT/MALYANMx00_F070CB.ld
  variants/STM32F0xx/F070CBT/startup_Mx00_f070xb.S
  variants/STM32F1xx/F103C4T_F103C6(T-U)/variant_BLUEPILL_F103C6.h
  variants/STM32F1xx/F103C8T_F103CB(T-U)/startup_M200_f103xb.S
  variants/STM32F1xx/F103C8T_F103CB(T-U)/variant_AFROFLIGHT_F103CB_XX.h
  variants/STM32F1xx/F103C8T_F103CB(T-U)/variant_MALYANM200_F103CB.h
  variants/STM32F1xx/F103C8T_F103CB(T-U)/variant_PILL_F103Cx.h
  variants/STM32F3xx/F303R(B-C)T/variant_OLIMEXINO_STM32F3.h
  variants/STM32F4xx/F413Z(G-H)(J-T)_F423ZH(J-T)/variant_DISCO_F413ZH.cpp
  variants/STM32H7xx/H742V(G-I)(H-T)_H743V(G-I)(H-T)_H750VBT_H753VI(H-T)/ldscript.ld
  variants/STM32L0xx/L072R(B-Z)T_L073R(B-Z)T_L083R(B-Z)T/variant_PX_HER0.h
  variants/STM32MP1xx/MP153AAC_MP153CAC_MP153DAC_MP153FAC_MP157AAC_MP157CAC_MP157DAC_MP157FAC/ldscript.ld
  variants/STM32MP1xx/MP153AAC_MP153CAC_MP153DAC_MP153FAC_MP157AAC_MP157CAC_MP157DAC_MP157FAC/variant_STM32MP157_DK.cpp
  variants/STM32WBxx/WB55C(C-E-G)U/ldscript.ld
  variants/STM32WBxx/WB55R(C-E-G)V/ldscript.ld
  variants/STM32WBxx/WB5MMGH/ldscript.ld
Labels: Fix

#1554 ci: add codespell action
  .github/workflows/CodeSpell.yml
  CI/codespell/.codespellignore
  CI/codespell/.codespellrc
  CI/codespell/codespell.md
  CI/update/stm32cube.py
  CI/update/stm32variant.py
  CI/utils/pathlib_ext.py
  CONTRIBUTING.md
  README.md
  cores/arduino/HardwareSerial.cpp
  cores/arduino/HardwareSerial.h
  cores/arduino/HardwareTimer.cpp
  cores/arduino/HardwareTimer.h
  cores/arduino/Print.h
  cores/arduino/Stream.h
  cores/arduino/WString.h
  cores/arduino/pins_arduino.h
  cores/arduino/stm32/OpenAMP/rsc_table.c
  cores/arduino/stm32/OpenAMP/virtio_buffer.c
  cores/arduino/stm32/PeripheralPins.h
  cores/arduino/stm32/usb/cdc/usbd_cdc.c
  cores/arduino/stm32/usb/hid/usbd_hid_composite.c
  cores/arduino/stm32/usb/hid/usbd_hid_composite_if.c
  cores/arduino/wiring_time.h
  libraries/EEPROM/README.md
  libraries/EEPROM/src/utility/stm32_eeprom.c
  libraries/IWatchdog/examples/IWDG_Button/IWDG_Button.ino
  libraries/IWatchdog/library.properties
  libraries/Keyboard/README.adoc
  libraries/Keyboard/library.properties
  libraries/Mouse/README.adoc
  libraries/Mouse/library.properties
  libraries/SPI/README.md
  libraries/SPI/examples/BarometricPressureSensor/BarometricPressureSensor.ino
  libraries/SPI/src/utility/spi_com.c
  libraries/SPI/src/utility/spi_com.h
  libraries/Servo/examples/fs90r/fs90r.ino
  libraries/Servo/src/Servo.h
  libraries/SoftwareSerial/examples/SoftwareSerialExample/SoftwareSerialExample.ino
  libraries/SoftwareSerial/examples/TwoPortReceive/TwoPortReceive.ino
  libraries/SoftwareSerial/src/SoftwareSerial.cpp
  libraries/SrcWrapper/src/stm32/analog.cpp
  libraries/SrcWrapper/src/stm32/pinmap.c
  libraries/SrcWrapper/src/syscalls.c
  libraries/Wire/examples/SFRRanger_reader/SFRRanger_reader.ino
  libraries/Wire/src/utility/twi.c
  platform.txt
  system/STM32F0xx/stm32f0xx_hal_conf_default.h
  variants/STM32L4xx/L475V(C-E-G)T_L476V(C-E-G)T_L486VGT/variant_B_L475E_IOT01A.cpp
Labels: Enhancement, Fix

#1549 HardwareTimer: start timer in case only CC interrupts are used
  cores/arduino/HardwareTimer.cpp
Labels: Fix

#1548 HardwareTimer: fix typo in comments and obvious ICPolarity wrong setting
  cores/arduino/HardwareTimer.cpp
Labels: Fix

#1558 HardwareTimer: remove useless variable timAssociatedInputChannel
  cores/arduino/HardwareTimer.cpp
Labels: Fix

#1552 Add a new variant for WeAct MiniSTM32H743VITX and MiniSTM32H750VBT
  README.md
  boards.txt
  variants/STM32H7xx/H742V(G-I)(H-T)_H743V(G-I)(H-T)_H750VBT_H753VI(H-T)/PeripheralPins_WeActMiniH7xx.c
  variants/STM32H7xx/H742V(G-I)(H-T)_H743V(G-I)(H-T)_H750VBT_H753VI(H-T)/variant_WeActMiniH7xx.cpp
  variants/STM32H7xx/H742V(G-I)(H-T)_H743V(G-I)(H-T)_H750VBT_H753VI(H-T)/variant_WeActMiniH7xx.h
Labels: New variant

#1563 Synchronize PlatformIO build scripts
  tools/platformio/boards_remap.json
  tools/platformio/platformio-build.py
Labels: Enhancement

#1573 variants: add DevEBox H743VITX and H750VBT support
  README.md
  boards.txt
  variants/STM32H7xx/H742V(G-I)(H-T)_H743V(G-I)(H-T)_H750VBT_H753VI(H-T)/PeripheralPins_DevEBoxH7xx.c
  variants/STM32H7xx/H742V(G-I)(H-T)_H743V(G-I)(H-T)_H750VBT_H753VI(H-T)/variant_DevEBoxH7xx.cpp
  variants/STM32H7xx/H742V(G-I)(H-T)_H743V(G-I)(H-T)_H750VBT_H753VI(H-T)/variant_DevEBoxH7xx.h
Labels: New variant
