Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2021-12, with the labels that each got.

#1559 Add variant for Daisy Petal SM
  README.md
  boards.txt
  variants/STM32H7xx/H742I(G-I)(K-T)_H743I(G-I)(K-T)_H750IB(K-T)_H753II(K-T)/PeripheralPins_DAISY_PETAL_SM.c
  variants/STM32H7xx/H742I(G-I)(K-T)_H743I(G-I)(K-T)_H750IB(K-T)_H753II(K-T)/variant_DAISY_PETAL_SM.cpp
  variants/STM32H7xx/H742I(G-I)(K-T)_H743I(G-I)(K-T)_H750IB(K-T)_H753II(K-T)/variant_DAISY_PETAL_SM.h
Labels: New variant

#1585 fix variant WeActMiniH7xx, DevEBoxH7xx: ena peripheral pll clks
  variants/STM32H7xx/H742V(G-I)(H-T)_H743V(G-I)(H-T)_H750VBT_H753VI(H-T)/variant_DevEBoxH7xx.cpp
  variants/STM32H7xx/H742V(G-I)(H-T)_H743V(G-I)(H-T)_H750VBT_H753VI(H-T)/variant_WeActMiniH7xx.cpp
Labels: Enhancement, Fix

#1595 Stm32 u5 update v1.0.2
  system/Drivers/STM32U5xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h
  system/Drivers/STM32U5xx_HAL_Driver/Inc/stm32u5xx_hal_dac.h
  system/Drivers/STM32U5xx_HAL_Driver/Inc/stm32u5xx_hal_dac_ex.h
  system/Drivers/STM32U5xx_HAL_Driver/Inc/stm32u5xx_hal_dma.h
  system/Drivers/STM32U5xx_HAL_Driver/Inc/stm32u5xx_ll_adc.h
  system/Drivers/STM32U5xx_HAL_Driver/Inc/stm32u5xx_ll_dac.h
  system/Drivers/STM32U5xx_HAL_Driver/Inc/stm32u5xx_ll_i2c.h
  system/Drivers/STM32U5xx_HAL_Driver/README.md
  system/Drivers/STM32U5xx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal.c
  system/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_adc.c
  system/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_adc_ex.c
  system/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_dac.c
  system/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_dac_ex.c
  system/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_dma.c
  system/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_dma_ex.c
  system/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_gtzc.c
  system/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_i2c.c
  system/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_rcc.c
  system/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_ll_dac.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement

#1589 Add support for generic STM32G030F6
  README.md
  boards.txt
  variants/STM32G0xx/G030F6P/generic_clock.c
  variants/STM32G0xx/G030F6P/ldscript.ld
Labels: New variant

#1602 interrupts: Disable EXTI when disabling interrupt
  libraries/SrcWrapper/src/stm32/interrupt.cpp
Labels: Bug :bug:
