Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2022-07, with the labels that each got.

#1759 fix(build_opt): add double quotes to allow space in path
  system/extras/prebuild.sh
Labels: Bug :bug:, Fix

#1764 System(g0) update stm32 G0xx HAL Drivers & CMSIS
  system/Drivers/CMSIS/Device/ST/STM32G0xx/Include/stm32g0xx.h
  system/Drivers/CMSIS/Device/ST/STM32G0xx/README.md
  system/Drivers/CMSIS/Device/ST/STM32YYxx_CMSIS_version.md
  system/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h
  system/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_hal_adc.h
  system/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_hal_adc_ex.h
  system/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_hal_hcd.h
  system/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_hal_i2c.h
  system/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_hal_irda.h
  system/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_hal_pcd.h
  system/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_hal_rtc.h
  system/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_hal_smartcard.h
  system/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_hal_uart.h
  system/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_hal_uart_ex.h
  system/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_hal_usart.h
  system/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_ll_adc.h
  system/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_ll_bus.h
  system/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_ll_lpuart.h
  system/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_ll_ucpd.h
  system/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_ll_usart.h
  system/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_ll_usb.h
  system/Drivers/STM32G0xx_HAL_Driver/LICENSE.md
  system/Drivers/STM32G0xx_HAL_Driver/README.md
  system/Drivers/STM32G0xx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal.c
  system/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_adc.c
  system/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_cec.c
  system/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_hcd.c
  system/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_i2c.c
  system/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_irda.c
  system/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rcc.c
  system/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rtc.c
  system/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_smartcard.c
  system/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_smbus.c
  system/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_uart.c
  system/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_uart_ex.c
  system/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_usart.c
  system/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c
  system/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.c
  system/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usb.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement, Fix

#1766 Fix for ADC timing for NUCLEO-WL55JC (STM32WLxx)
  libraries/SrcWrapper/src/stm32/analog.cpp
Labels: Bug :bug:, Fix

#1769 arduino-lint 1.2.1 requirements fix prevents upload with arduino-cli
  .github/workflows/arduino-lint.yml
  boards.txt
  platform.txt
Labels: Bug :bug:, Fix

#1771 fix(SoftwareSerial): correct TX to RX switch when using half-duplex
  libraries/SoftwareSerial/src/SoftwareSerial.cpp
Labels: Enhancement

#1775 fix(wire): ensure i2c bus is ready
  libraries/Wire/src/utility/twi.c
Labels: Bug :bug:, Fix
