Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2022-05, with the labels that each got.

#1704 Add flags about fpv4 for cortex-m33 on platformio-build.py
  tools/platformio/platformio-build.py
Labels: Enhancement

#1711 chore: Prepare for next STM32CubeProgrammer release
  boards.txt
Labels: Fix

#1702 fix: make micros compatible with ISR
  libraries/SrcWrapper/src/stm32/clock.c
Labels: Enhancement, Fix

#1708 Cleaning the build process
  libraries/SrcWrapper/src/HardwareTimer.cpp
  libraries/SrcWrapper/src/new.cpp
  platform.txt
Labels: Enhancement, Arduino compatibility, Fix

#1715 Add support to CRC peripheral by default
  cores/arduino/stm32/stm32yyxx_hal_conf.h
  libraries/SrcWrapper/src/stm32/clock.c
  libraries/SrcWrapper/src/stm32/hw_config.c
Labels: Enhancement

#1716 fix: allow to disable HAL CRC module
  cores/arduino/stm32/stm32yyxx_hal_conf.h
  libraries/SrcWrapper/src/stm32/clock.c
  libraries/SrcWrapper/src/stm32/hw_config.c
Labels: Fix

#1721 HardwareTimer: call refresh() after parameter update when timer not running
  cores/arduino/HardwareTimer.h
  libraries/SrcWrapper/src/HardwareTimer.cpp
Labels: Enhancement

#1722 Improve Swan initialization
  variants/STM32L4xx/L4R5Z(G-I)Y_L4R9Z(G-I)Y_L4S5ZIY_L4S9ZIY/variant_SWAN_R5.cpp
Labels: Enhancement

#1725 feat: allows arduino-cli to override build property
  boards.txt
  platform.txt
Labels: Arduino compatibility

#1729 Improve support for hand-written asm source files
  tools/platformio/platformio-build.py
Labels: Enhancement

#1712 Added F722RE Variant to boards.txt, added F722RE ldscript.ld
  boards.txt
  variants/STM32F7xx/F722R(C-E)T_F730R8T_F732RET/generic_clock.c
  variants/STM32F7xx/F722R(C-E)T_F730R8T_F732RET/ldscript.ld
Labels: New variant
