Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2022-04, with the labels that each got.

#1684 system(WB) update STM32WBxx HAL Drivers to v1.10.1 and CMSIS Drivers to v1.10.1
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Include/stm32wb10xx.h
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Include/stm32wb15xx.h
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Include/stm32wbxx.h
  system/Drivers/CMSIS/Device/ST/STM32WBxx/README.md
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Release_Notes.html
  system/Drivers/CMSIS/Device/ST/STM32YYxx_CMSIS_version.md
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_adc.h
  system/Drivers/STM32WBxx_HAL_Driver/README.md
  system/Drivers/STM32WBxx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_adc.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_adc.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement

#1694 fix: Stabilize SWD Programming for Swan (STM32L4R5)
  boards.txt
Labels: Enhancement, Fix

#1697 core: fix HardwareSerial compilation failed when USART disabled
  cores/arduino/HardwareSerial.h
Labels: Fix

#1691 wire: add fix for toggling NoStretch
  libraries/Wire/src/Wire.cpp
  libraries/Wire/src/Wire.h
  libraries/Wire/src/utility/twi.c
  libraries/Wire/src/utility/twi.h
Labels: Enhancement
