Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2022-09, with the labels that each got.

#1824 fix: set only AF mode for mcu with single AF
  cores/arduino/stm32/stm32_def.h
  libraries/SrcWrapper/src/stm32/pinmap.c
Labels: Bug :bug:, Fix

#1796 Added Generic L0xx Boards
  README.md
  boards.txt
  variants/STM32L0xx/L010C6T/generic_clock.c
  variants/STM32L0xx/L010C6T/ldscript.ld
  variants/STM32L0xx/L010F4P_L011F(3-4)P_L021F4P/generic_clock.c
  variants/STM32L0xx/L010F4P_L011F(3-4)P_L021F4P/ldscript.ld
  variants/STM32L0xx/L010K4T_L011K(3-4)T_L021K4T/generic_clock.c
  variants/STM32L0xx/L010K4T_L011K(3-4)T_L021K4T/ldscript.ld
  variants/STM32L0xx/L010R8T/generic_clock.c
  variants/STM32L0xx/L010R8T/ldscript.ld
  variants/STM32L0xx/L011D(3-4)P_L021D4P/generic_clock.c
  variants/STM32L0xx/L011D(3-4)P_L021D4P/ldscript.ld
  variants/STM32L0xx/L011E(3-4)Y/generic_clock.c
  variants/STM32L0xx/L011E(3-4)Y/ldscript.ld
  variants/STM32L0xx/L011F(3-4)U_L021F4U/generic_clock.c
  variants/STM32L0xx/L011F(3-4)U_L021F4U/ldscript.ld
  variants/STM32L0xx/L011G(3-4)U_L021G4U/generic_clock.c
  variants/STM32L0xx/L011G(3-4)U_L021G4U/ldscript.ld
  variants/STM32L0xx/L011K(3-4)U_L021K4U/generic_clock.c
  variants/STM32L0xx/L011K(3-4)U_L021K4U/ldscript.ld
  variants/STM32L0xx/L031C(4-6)(T-U)_L041C4T_L041C6(T-U)/generic_clock.c
  variants/STM32L0xx/L031C(4-6)(T-U)_L041C4T_L041C6(T-U)/ldscript.ld
  variants/STM32L0xx/L031E(4-6)Y_L041E6Y/generic_clock.c
  variants/STM32L0xx/L031E(4-6)Y_L041E6Y/ldscript.ld
  variants/STM32L0xx/L031F(4-6)P_L041F6P/generic_clock.c
  variants/STM32L0xx/L031F(4-6)P_L041F6P/ldscript.ld
  variants/STM32L0xx/L031G(4-6)U_L041G6U/generic_clock.c
  variants/STM32L0xx/L031G(4-6)U_L041G6U/ldscript.ld
  variants/STM32L0xx/L052C(6-8)(T-U)_L053C(6-8)(T-U)_L062C8U_L063C8(T-U)/generic_clock.c
  variants/STM32L0xx/L052C(6-8)(T-U)_L053C(6-8)(T-U)_L062C8U_L063C8(T-U)/ldscript.ld
  variants/STM32L0xx/L052K(6-8)T_L062K8T/generic_clock.c
  variants/STM32L0xx/L052K(6-8)T_L062K8T/ldscript.ld
  variants/STM32L0xx/L052R(6-8)H_L053R(6-8)H/generic_clock.c
  variants/STM32L0xx/L052R(6-8)H_L053R(6-8)H/ldscript.ld
  variants/STM32L0xx/L052T6Y_L052T8(F-Y)/generic_clock.c
  variants/STM32L0xx/L052T6Y_L052T8(F-Y)/ldscript.ld
  variants/STM32L0xx/L072C(B-Z)(T-U)_L073C(B-Z)(T-U)_L082CZU_L083CBT_L083CZ(T-U)/generic_clock.c
  variants/STM32L0xx/L072C(B-Z)(T-U)_L073C(B-Z)(T-U)_L082CZU_L083CBT_L083CZ(T-U)/ldscript.ld
  variants/STM32L0xx/L072K(B-Z)U_L082K(B-Z)U/generic_clock.c
  variants/STM32L0xx/L072K(B-Z)U_L082K(B-Z)U/ldscript.ld
  variants/STM32L0xx/L072R(B-Z)(H-I)_L073RBH_L073RZ(H-I)_L083R(B-Z)H/generic_clock.c
  variants/STM32L0xx/L072R(B-Z)(H-I)_L073RBH_L073RZ(H-I)_L083R(B-Z)H/ldscript.ld
  variants/STM32L0xx/L072V(8-B-Z)(I-T)_L073V(8-B-Z)(I-T)_L083V(8-B-Z)(I-T)/generic_clock.c
  variants/STM32L0xx/L072V(8-B-Z)(I-T)_L073V(8-B-Z)(I-T)_L083V(8-B-Z)(I-T)/ldscript.ld
Labels: New variant

#1825 fix: typo "..build.peripheral_pins"
  boards.txt
Labels: Fix

#1831 Add Nucleo F722ZE board
  README.md
  boards.txt
  variants/STM32F7xx/F722Z(C-E)T_F732ZET/generic_clock.c
  variants/STM32F7xx/F722Z(C-E)T_F732ZET/ldscript.ld
  variants/STM32F7xx/F722Z(C-E)T_F732ZET/variant_NUCLEO_F722ZE.cpp
  variants/STM32F7xx/F722Z(C-E)T_F732ZET/variant_NUCLEO_F722ZE.h
Labels: New variant

#1826 Core debug hardening
  cores/arduino/stm32/uart.h
  libraries/SrcWrapper/src/stm32/uart.c
  libraries/SrcWrapper/src/syscalls.c
Labels: Bug :bug:, Enhancement, Fix

#1836 fix: U575Z(G-I)TxQ_U585ZITxQ ram issue
  boards.txt
  variants/STM32U5xx/U575Z(G-I)TxQ_U585ZITxQ/boards_entry.txt
  variants/STM32U5xx/U575Z(G-I)TxQ_U585ZITxQ/ldscript.ld
Labels: Fix
