Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2022-02, with the labels that each got.

#1634 [U(S)ART] hardware flow control support
  cores/arduino/HardwareSerial.cpp
  cores/arduino/HardwareSerial.h
  cores/arduino/stm32/uart.h
  libraries/SrcWrapper/src/stm32/uart.c
Labels: New feature

#1639 system(U5): HAL RCC should restore PWR clock after clock configuration
  system/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_rcc.c
Labels: Fix

#1640 cores(U5): support USB Type-C on U5
  cores/arduino/stm32/usb/usbd_conf.c
  cores/arduino/stm32/usb/usbd_conf.h
  variants/STM32L5xx/L552Z(C-E)TxQ_L562ZETxQ/variant_NUCLEO_L552ZE_Q.h
  variants/STM32U5xx/U575A(G-I)IxQ_U585AIIxQ/variant_B_U585I_IOT02A.h
  variants/STM32U5xx/U575Z(G-I)TxQ_U585ZETxQ/variant_NUCLEO_U575ZI_Q.h
Labels: Enhancement

#1658 fix(cli): optional column number in error pattern
  CI/build/arduino-cli.py
Labels: Fix

#1653 Bootloader jump to application
  system/STM32F0xx/system_stm32f0xx.c
  system/STM32F1xx/system_stm32f1xx.c
  system/STM32F2xx/system_stm32f2xx.c
  system/STM32F3xx/system_stm32f3xx.c
  system/STM32F4xx/system_stm32f4xx.c
  system/STM32F7xx/system_stm32f7xx.c
  system/STM32G0xx/system_stm32g0xx.c
  system/STM32G4xx/system_stm32g4xx.c
  system/STM32H7xx/system_stm32h7xx.c
  system/STM32L0xx/system_stm32l0xx.c
  system/STM32L1xx/system_stm32l1xx.c
  system/STM32L4xx/system_stm32l4xx.c
  system/STM32L5xx/system_stm32l5xx_ns.c
  system/STM32U5xx/system_stm32u5xx.c
  system/STM32WBxx/system_stm32wbxx.c
  system/STM32WLxx/system_stm32wlxx.c
Labels: Bug :bug:, Fix

#1655 add STM32G031FxPx (and STM32G031Y8Yx, STM32G041F6Px, STM32G041F8Px STM32G041Y8Yx)
  README.md
  boards.txt
  variants/STM32G0xx/G031F(4-6-8)P_G031Y8Y_G041F(6-8)P_G041Y8Y/generic_clock.c
  variants/STM32G0xx/G031F(4-6-8)P_G031Y8Y_G041F(6-8)P_G041Y8Y/ldscript.ld
Labels: New variant

#1663 Wire: implement STOP sequence to recover I2C bus.
  libraries/Wire/src/Wire.cpp
  libraries/Wire/src/Wire.h
Labels: Enhancement
