Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2023-01, with the labels that each got.

#1920 fix: remove RTC clock source selection for Nucleo_F446
  variants/STM32F4xx/F446R(C-E)T/variant_NUCLEO_F446RE.cpp
Labels: Fix

#1930 map LED_BUILTIN to PA13
  variants/STM32G0xx/G0B1C(B-C-E)(T-U)_G0C1C(C-E)(T-U)/variant_EBB42_V1_1.h
Labels: Enhancement

#1932 fix: USB configuration STM32H723ZG
  cores/arduino/stm32/usb/usbd_conf.h
  variants/STM32H7xx/H723Z(E-G)T_H730ZBT_H733ZGT/generic_clock.c
  variants/STM32H7xx/H723Z(E-G)T_H730ZBT_H733ZGT/variant_NUCLEO_H723ZG.cpp
Labels: Enhancement, Fix
