Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2023-07, with the labels that each got.

#2049 variants(C0): add STM32C0116-DK support
  README.md
  boards.txt
  cmake/boards_db.cmake
  variants/STM32C0xx/C011D6Y_C011F(4-6)(P-U)_C031F(4-6)P/CMakeLists.txt
  variants/STM32C0xx/C011D6Y_C011F(4-6)(P-U)_C031F(4-6)P/variant_STM32C0116_DK.cpp
  variants/STM32C0xx/C011D6Y_C011F(4-6)(P-U)_C031F(4-6)P/variant_STM32C0116_DK.h
Labels: New variant

#2061 system(H7): allow VECT_TAB_BASE_ADDRESS redefinition
  system/STM32H7xx/system_stm32h7xx.c
  system/STM32WLxx/system_stm32wlxx.c
Labels: Enhancement

#2060 make cmake work on macos
  cmake/FindArduinoCtags.cmake
  cmake/ensure_core_deps.cmake
Labels: Fix

#2080 feat: allow USE_HAL_PPP_REGISTER_CALLBACKS redefinition
  system/STM32C0xx/stm32c0xx_hal_conf_default.h
  system/STM32F0xx/stm32f0xx_hal_conf_default.h
  system/STM32F1xx/stm32f1xx_hal_conf_default.h
  system/STM32F2xx/stm32f2xx_hal_conf_default.h
  system/STM32F3xx/stm32f3xx_hal_conf_default.h
  system/STM32F4xx/stm32f4xx_hal_conf_default.h
  system/STM32F7xx/stm32f7xx_hal_conf_default.h
  system/STM32G0xx/stm32g0xx_hal_conf_default.h
  system/STM32G4xx/stm32g4xx_hal_conf_default.h
  system/STM32H5xx/stm32h5xx_hal_conf_default.h
  system/STM32H7xx/stm32h7xx_hal_conf_default.h
  system/STM32L0xx/stm32l0xx_hal_conf_default.h
  system/STM32L1xx/stm32l1xx_hal_conf_default.h
  system/STM32L4xx/stm32l4xx_hal_conf_default.h
  system/STM32L5xx/stm32l5xx_hal_conf_default.h
  system/STM32MP1xx/stm32mp1xx_hal_conf_default.h
  system/STM32U5xx/stm32u5xx_hal_conf_default.h
  system/STM32WBxx/stm32wbxx_hal_conf_default.h
  system/STM32WLxx/stm32wlxx_hal_conf_default.h
Labels: Enhancement
