Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2023-04, with the labels that each got.

#1993 feat: add offset option to stm32CubeProg upload method
  boards.txt
  platform.txt
Labels: Enhancement

#1996 Update to latest STM32CubeWB v1.16.0
  system/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_cortex.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_dma.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_flash.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_flash_ex.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_gpio.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_gpio_ex.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_i2c.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_ipcc.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_pwr.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_pwr_ex.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_rcc_ex.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_sai.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_smbus.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_tsc.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_bus.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_cortex.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_dma.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_dmamux.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_gpio.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_i2c.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_ipcc.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_pwr.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_rcc.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_utils.h
  system/Drivers/STM32WBxx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_cortex.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_dma.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_dma_ex.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_flash.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_flash_ex.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_i2c.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_ipcc.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr_ex.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rcc.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_smbus.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_timebase_rtc_alarm_template.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_timebase_rtc_wakeup_template.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_timebase_tim_template.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_tsc.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_dma.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_gpio.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_i2c.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_pwr.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_rcc.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_utils.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement, Fix

#1999 GNSE clock config update and moved to LoRa menu
  boards.txt
  variants/STM32WLxx/WL54CCU_WL55CCU_WLE4C(8-B-C)U_WLE5C(8-B-C)U/variant_GENERIC_NODE_SE_TTI.cpp
Labels: Fix

#2007 fix(Nucleo_F401RE): use HSI intead of HSE bypass
  variants/STM32F4xx/F401R(B-C-D-E)T/variant_NUCLEO_F401RE.cpp
Labels: Fix

#2005 Add RAK3172 module
  README.md
  boards.txt
  variants/STM32WLxx/WL54CCU_WL55CCU_WLE4C(8-B-C)U_WLE5C(8-B-C)U/variant_RAK3172_MODULE.cpp
  variants/STM32WLxx/WL54CCU_WL55CCU_WLE4C(8-B-C)U_WLE5C(8-B-C)U/variant_RAK3172_MODULE.h
Labels: New variant
