Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2023-08, with the labels that each got.

#2095 fix(H7): restore DATA_IN_D2_SRAM comment in system source file
  system/STM32H7xx/system_stm32h7xx.c
Labels: Fix

#2099 chore: update to CMSIS 5.9.0
  .github/actions/pio-build/README.md
  .github/actions/pio-build/action.yml
  CI/update/stm32wrapper.py
  boards.txt
  cmake/boards_db.cmake
  cmake/templates/boards_db.cmake
  libraries/CMSIS_DSP/src/BasicMathFunctions/BasicMathFunctionsF16.c
  libraries/CMSIS_DSP/src/BayesFunctions/BayesFunctionsF16.c
  libraries/CMSIS_DSP/src/CommonTables/CommonTablesF16.c
  libraries/CMSIS_DSP/src/ComplexMathFunctions/ComplexMathFunctionsF16.c
  libraries/CMSIS_DSP/src/DistanceFunctions/DistanceFunctionsF16.c
  libraries/CMSIS_DSP/src/FastMathFunctions/FastMathFunctionsF16.c
  libraries/CMSIS_DSP/src/FilteringFunctions/FilteringFunctionsF16.c
  libraries/CMSIS_DSP/src/InterpolationFunctions/InterpolationFunctions.c
  libraries/CMSIS_DSP/src/InterpolationFunctions/InterpolationFunctionsF16.c
  libraries/CMSIS_DSP/src/MatrixFunctions/MatrixFunctionsF16.c
  libraries/CMSIS_DSP/src/QuaternionMathFunctions/QuaternionMathFunctions.c
  libraries/CMSIS_DSP/src/SVMFunctions/SVMFunctionsF16.c
  libraries/CMSIS_DSP/src/StatisticsFunctions/StatisticsFunctionsF16.c
  libraries/CMSIS_DSP/src/SupportFunctions/SupportFunctionsF16.c
  libraries/CMSIS_DSP/src/TransformFunctions/TransformFunctionsF16.c
  platform.txt
  tools/platformio/platformio-build.py
Labels: Enhancement

#2097 fix(Nucleo_G031K8): add new node name
  boards.txt
Labels: Fix

#2100 chore(pio): disable build
  .github/workflows/PIO-build.yml
Labels: Fix

#2108 Add variant: add support for generic F446Z(C-E)(H-J-T) and Nucleo-F446ZE
  README.md
  boards.txt
  variants/STM32F4xx/F446Z(C-E)(H-J-T)/generic_clock.c
  variants/STM32F4xx/F446Z(C-E)(H-J-T)/ldscript.ld
  variants/STM32F4xx/F446Z(C-E)(H-J-T)/variant_NUCLEO_F446ZE.cpp
  variants/STM32F4xx/F446Z(C-E)(H-J-T)/variant_NUCLEO_F446ZE.h
Labels: New variant
