Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2023-10, with the labels that each got.

#2148 fix(Wire): avoid memory leaks
  libraries/Wire/src/Wire.cpp
  libraries/Wire/src/Wire.h
Labels: Fix

#2151 feat: implement weaked _gettimeofday
  cores/arduino/wiring_time.h
Labels: Enhancement

#2153 fix(backup): enable RTC clock for TAMP backup registers
  cores/arduino/stm32/backup.h
Labels: Bug :bug:, Fix

#2155 Wrap cmake policies in if statements
  cmake/FindArduinoCtags.cmake
  cmake/ensure_core_deps.cmake
Labels: Enhancement
