Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2023-03, with the labels that each got.

#1961 swan_r5: Increase LSE drive strength
  variants/STM32L4xx/L4R5Z(G-I)Y_L4R9Z(G-I)Y_L4S5ZIY_L4S9ZIY/variant_SWAN_R5.cpp
Labels: Enhancement

#1964 fix(serial): warning Warray-bounds
  cores/arduino/HardwareSerial.cpp
Labels: Fix

#1971 fix: typos raised by new codespell version
  libraries/CMSIS_DSP/examples/arm_sin_cos_example_f32/arm_sin_cos_example_f32.ino
  libraries/SoftwareSerial/src/SoftwareSerial.cpp
  libraries/SrcWrapper/src/stm32/uart.c
  libraries/Wire/examples/i2c_scanner/i2c_scanner.ino
Labels: Fix

#1972 fix: silence the warnings from ExternalProject_Add
  cmake/FindArduinoCtags.cmake
  cmake/ensure_core_deps.cmake
Labels: Enhancement, Fix

#1976 Add debug openocd
  CI/update/stm32variant.py
  platform.txt
  system/extras/postbuild.sh
  variants/STM32F0xx/openocd.cfg
  variants/STM32F1xx/openocd.cfg
  variants/STM32F2xx/openocd.cfg
  variants/STM32F3xx/openocd.cfg
  variants/STM32F4xx/openocd.cfg
  variants/STM32F7xx/openocd.cfg
  variants/STM32G0xx/openocd.cfg
  variants/STM32G4xx/openocd.cfg
  variants/STM32H7xx/openocd.cfg
  variants/STM32L0xx/openocd.cfg
  variants/STM32L1xx/openocd.cfg
  variants/STM32L4xx/openocd.cfg
  variants/STM32L5xx/openocd.cfg
  variants/STM32MP1xx/openocd.cfg
  variants/STM32U5xx/openocd.cfg
  variants/STM32WBxx/openocd.cfg
  variants/STM32WLxx/openocd.cfg
Labels: Enhancement, Arduino compatibility

#1985 variant(WB): add P-Nucleo WB55 USB Dongle
  README.md
  boards.txt
  variants/STM32WBxx/WB35C(C-E)UxA_WB55C(C-E-G)U/variant_P_NUCLEO_WB55_USB_DONGLE.cpp
  variants/STM32WBxx/WB35C(C-E)UxA_WB55C(C-E-G)U/variant_P_NUCLEO_WB55_USB_DONGLE.h
Labels: New variant

#1987 Add SparkFun MicroMod STM32F405
  CI/build/conf/cores_config.json
  README.md
  boards.txt
  cmake/boards_db.cmake
  tools/platformio/boards_remap.json
  variants/STM32F4xx/F405RGT_F415RGT/CMakeLists.txt
  variants/STM32F4xx/F405RGT_F415RGT/PeripheralPins_MICROMOD_F405.c
  variants/STM32F4xx/F405RGT_F415RGT/variant_MICROMOD_F405.cpp
  variants/STM32F4xx/F405RGT_F415RGT/variant_MICROMOD_F405.h
Labels: New variant
