Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2023-02, with the labels that each got.

#1937 Fix issue on upload for old NUCLEO-F401RE boards
  boards.txt
Labels: Fix

#1941 fix(CRC): explicitly set InputDataFormat to avoid assert
  libraries/SrcWrapper/src/stm32/hw_config.c
Labels: Fix

#1944 platform: moved from arm-none-eabi-gcc 10.3.1-2.3 to 12.2.1-1.2
  CI/update/templates/stm32yyxx_ll.h
  CI/update/templates/stm32yyxx_ll_ppp.h
  cores/arduino/avr/dtostrf.c
  cores/arduino/stm32/LL/stm32yyxx_ll.h
  cores/arduino/stm32/LL/stm32yyxx_ll_adc.h
  cores/arduino/stm32/LL/stm32yyxx_ll_bdma.h
  cores/arduino/stm32/LL/stm32yyxx_ll_bus.h
  cores/arduino/stm32/LL/stm32yyxx_ll_comp.h
  cores/arduino/stm32/LL/stm32yyxx_ll_cordic.h
  cores/arduino/stm32/LL/stm32yyxx_ll_cortex.h
  cores/arduino/stm32/LL/stm32yyxx_ll_crc.h
  cores/arduino/stm32/LL/stm32yyxx_ll_crs.h
  cores/arduino/stm32/LL/stm32yyxx_ll_dac.h
  cores/arduino/stm32/LL/stm32yyxx_ll_dcache.h
  cores/arduino/stm32/LL/stm32yyxx_ll_delayblock.h
  cores/arduino/stm32/LL/stm32yyxx_ll_dlyb.h
  cores/arduino/stm32/LL/stm32yyxx_ll_dma.h
  cores/arduino/stm32/LL/stm32yyxx_ll_dma2d.h
  cores/arduino/stm32/LL/stm32yyxx_ll_dmamux.h
  cores/arduino/stm32/LL/stm32yyxx_ll_exti.h
  cores/arduino/stm32/LL/stm32yyxx_ll_fmac.h
  cores/arduino/stm32/LL/stm32yyxx_ll_fmc.h
  cores/arduino/stm32/LL/stm32yyxx_ll_fmpi2c.h
  cores/arduino/stm32/LL/stm32yyxx_ll_fsmc.h
  cores/arduino/stm32/LL/stm32yyxx_ll_gpio.h
  cores/arduino/stm32/LL/stm32yyxx_ll_hrtim.h
  cores/arduino/stm32/LL/stm32yyxx_ll_hsem.h
  cores/arduino/stm32/LL/stm32yyxx_ll_i2c.h
  cores/arduino/stm32/LL/stm32yyxx_ll_icache.h
  cores/arduino/stm32/LL/stm32yyxx_ll_ipcc.h
  cores/arduino/stm32/LL/stm32yyxx_ll_iwdg.h
  cores/arduino/stm32/LL/stm32yyxx_ll_lpgpio.h
  cores/arduino/stm32/LL/stm32yyxx_ll_lptim.h
  cores/arduino/stm32/LL/stm32yyxx_ll_lpuart.h
  cores/arduino/stm32/LL/stm32yyxx_ll_mdma.h
  cores/arduino/stm32/LL/stm32yyxx_ll_opamp.h
  cores/arduino/stm32/LL/stm32yyxx_ll_pka.h
  cores/arduino/stm32/LL/stm32yyxx_ll_pwr.h
  cores/arduino/stm32/LL/stm32yyxx_ll_rcc.h
  cores/arduino/stm32/LL/stm32yyxx_ll_rng.h
  cores/arduino/stm32/LL/stm32yyxx_ll_rtc.h
  cores/arduino/stm32/LL/stm32yyxx_ll_sdmmc.h
  cores/arduino/stm32/LL/stm32yyxx_ll_spi.h
  cores/arduino/stm32/LL/stm32yyxx_ll_swpmi.h
  cores/arduino/stm32/LL/stm32yyxx_ll_system.h
  cores/arduino/stm32/LL/stm32yyxx_ll_tim.h
  cores/arduino/stm32/LL/stm32yyxx_ll_ucpd.h
  cores/arduino/stm32/LL/stm32yyxx_ll_usart.h
  cores/arduino/stm32/LL/stm32yyxx_ll_usb.h
  cores/arduino/stm32/LL/stm32yyxx_ll_utils.h
  cores/arduino/stm32/LL/stm32yyxx_ll_wwdg.h
  platform.txt
Labels: Enhancement

#1949 chore: unified maple upload method
  platform.txt
Labels: Enhancement, Arduino compatibility

#1958 ci: deploy check on Markdown links
  .github/workflows/MarkdwonLinksCheck.yml
  README.md
  variants/STM32MP1xx/MP153AAC_MP153CAC_MP153DAC_MP153FAC_MP157AAC_MP157CAC_MP157DAC_MP157FAC/README.md
Labels: Enhancement, Fix

#1959 ci: cleanup to avoid useless execution
  .github/workflows/Arduino-build.yml
  .github/workflows/Cmake.yml
  .github/workflows/PIO-build.yml
Labels: Enhancement
