Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2023-11, with the labels that each got.

#2165 external redefinition of CDC_TRANSMIT_QUEUE_BUFFER_PACKET_NUMBER and CDC_RECEIVE_QUEUE_BUFFER_PACKET_NUMBER
  cores/arduino/stm32/usb/cdc/cdc_queue.h
Labels: Enhancement

#2182 fix(SPI): avoid 0 delay when SPI clock > 1MHz
  libraries/SPI/src/utility/spi_com.c
Labels: Fix

#2171 [breaking] SPI library rework
  CI/build/examples/BareMinimum/BareMinimum.ino
  libraries/SPI/README.md
  libraries/SPI/src/SPI.cpp
  libraries/SPI/src/SPI.h
  libraries/SPI/src/utility/spi_com.c
  libraries/SPI/src/utility/spi_com.h
Labels: Enhancement, Arduino compatibility

#2184 feat: support compiler.optimization_flags for Arduino IDE 2.X
  platform.txt
Labels: Arduino compatibility

#2174 Add Generic F723-F730-F733 Variants
  README.md
  boards.txt
  variants/STM32F7xx/F723I(C-E)(K-T)_F730I8K_F733IE(K-T)/generic_clock.c
  variants/STM32F7xx/F723I(C-E)(K-T)_F730I8K_F733IE(K-T)/ldscript.ld
Labels: New variant

#2186 fix(nucleo_G474RE): wrong SystemClock_Config configuration
  variants/STM32G4xx/G473R(B-C-E)T_G474R(B-C-E)T_G483RET_G484RET/variant_NUCLEO_G474RE.cpp
Labels: Fix

#2187 fix(nucleo_G431KB): add missing analog pin
  variants/STM32G4xx/G431K(6-8-B)(T-U)_G441KB(T-U)/variant_NUCLEO_G431KB.cpp
  variants/STM32G4xx/G431K(6-8-B)(T-U)_G441KB(T-U)/variant_NUCLEO_G431KB.h
Labels: Fix

#2191 Fixed SPI mode enum in SubGHz library
  libraries/SubGhz/src/SubGhz.h
Labels: Bug :bug:, Fix

#2193 fix(SubGhz): SPISettings not properly defined
  libraries/SubGhz/src/SubGhz.cpp
  libraries/SubGhz/src/SubGhz.h
Labels: Bug :bug:, Fix

#2196 Fixed memory on Wire instance
  libraries/Wire/src/Wire.cpp
Labels: Bug :bug:, Fix

#2200 fix(nucleo_f722ze): remove duplicate PE2 definition
  variants/STM32F7xx/F722Z(C-E)T_F732ZET/variant_NUCLEO_F722ZE.h
Labels: Bug :bug:, Fix

#2198 chore(U5): update to latest STM32CubeU5 v1.4.0
  system/Drivers/CMSIS/Device/ST/STM32U5xx/Include/Templates/partition_stm32u595xx.h
  system/Drivers/CMSIS/Device/ST/STM32U5xx/Include/Templates/partition_stm32u5f7xx.h
  system/Drivers/CMSIS/Device/ST/STM32U5xx/Include/stm32u5f7xx.h
  system/Drivers/CMSIS/Device/ST/STM32U5xx/Include/stm32u5g7xx.h
  system/Drivers/CMSIS/Device/ST/STM32U5xx/Include/stm32u5xx.h
  system/Drivers/CMSIS/Device/ST/STM32U5xx/Release_Notes.html
  system/Drivers/CMSIS/Device/ST/STM32YYxx_CMSIS_version.md
  system/Drivers/STM32U5xx_HAL_Driver/Inc/stm32u5xx_hal_adc.h
  system/Drivers/STM32U5xx_HAL_Driver/Inc/stm32u5xx_ll_adc.h
  system/Drivers/STM32U5xx_HAL_Driver/README.md
  system/Drivers/STM32U5xx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal.c
  system/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_adc_ex.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement, Fix

#2204 [spi]: Keep constexpr constructor
  libraries/SPI/README.md
  libraries/SPI/src/SPI.cpp
  libraries/SPI/src/SPI.h
  libraries/SubGhz/src/SubGhz.cpp
  libraries/SubGhz/src/SubGhz.h
Labels: Enhancement, Fix

#2206 feat(spi): add transfer api with tx and rx buffer
  libraries/SPI/README.md
  libraries/SPI/src/SPI.cpp
  libraries/SPI/src/SPI.h
  libraries/SPI/src/utility/spi_com.c
  libraries/SPI/src/utility/spi_com.h
Labels: Enhancement, Arduino compatibility
