Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2023-09, with the labels that each got.

#2123 fix(clock): handle HSE TCXO when available
  libraries/SrcWrapper/src/stm32/clock.c
Labels: Fix

#2124 feat(serial): add timeout support to flush()
  cores/arduino/HardwareSerial.cpp
  cores/arduino/HardwareSerial.h
  cores/arduino/stm32/uart.h
Labels: Enhancement, Fix

#2126 chore: prevent old gcc version to raised an error
  libraries/SrcWrapper/src/stm32/clock.c
Labels: Enhancement

#2130 Support for NUCLEO-H753ZI board
  README.md
  boards.txt
  variants/STM32H7xx/H742Z(G-I)T_H743Z(G-I)T_H747A(G-I)I_H747I(G-I)T_H750ZBT_H753ZIT_H757AII_H757IIT/CMakeLists.txt
  variants/STM32H7xx/H742Z(G-I)T_H743Z(G-I)T_H747A(G-I)I_H747I(G-I)T_H750ZBT_H753ZIT_H757AII_H757IIT/variant_NUCLEO_H753ZI.cpp
  variants/STM32H7xx/H742Z(G-I)T_H743Z(G-I)T_H747A(G-I)I_H747I(G-I)T_H750ZBT_H753ZIT_H757AII_H757IIT/variant_NUCLEO_H753ZI.h
Labels: New variant

#2135 Update PlatformIO build script
  tools/platformio/platformio-build.py
Labels: Enhancement, Fix

#2136 Add support for setting the channel input filter
  cores/arduino/HardwareTimer.h
  libraries/SrcWrapper/src/HardwareTimer.cpp
Labels: Enhancement
