Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2024-11, with the labels that each got.

#2544 fix: print(0ULL) output nothing
  cores/arduino/Print.cpp
Labels: fix :adhesive_bandage:

#2548 fix(doc): broken url
  .github/workflows/MarkdwonLinksCheck.yml
  README.md
  libraries/SPI/README.md
Labels: fix :adhesive_bandage:

#2549 fix(spi): ensure spi_t structure properly init
  libraries/SPI/src/SPI.cpp
  libraries/SPI/src/SPI.h
Labels: enhancement, fix :adhesive_bandage:

#2553 refactor(i2c): simplify constructor
  libraries/Wire/src/Wire.cpp
  libraries/Wire/src/Wire.h
Labels: enhancement

#2566 chore: update to xpack-openocd v0.12.0-4
  platform.txt
Labels: enhancement

#2568 variants(f4): custom peripheral pins for Nucleo-F4x9ZI
  boards.txt
  variants/STM32F4xx/F427Z(G-I)T_F429ZET_F429Z(G-I)(T-Y)_F437Z(G-I)T_F439Z(G-I)(T-Y)/PeripheralPins_NUCLEO_F4x9ZI.c
Labels: enhancement

#2584 chore(c0): enable usb
  boards.txt
  variants/STM32C0xx/C071R(8-B)T/generic_clock.c
  variants/STM32C0xx/C071R(8-B)T/variant_NUCLEO_C071RB.cpp
Labels: enhancement
