Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2024-01, with the labels that each got.

#2238 Update README.md
  README.md
Labels: Documentation :books:, Fix

#2247 fix(platform): wrong optimization_flags for Arduino 1.8.x
  platform.txt
Labels: Bug :bug:, Fix

#2249 chore: update to latest STM32CubeWB v1.18.0
  system/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_i2c.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_lptim.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_rtc_ex.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_smbus.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_tim.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_i2c.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_tim.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_usb.h
  system/Drivers/STM32WBxx_HAL_Driver/LICENSE.md
  system/Drivers/STM32WBxx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_i2c.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_lptim.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_sai.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_smbus.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_tim.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_tim_ex.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_tim.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement, Fix

#2253 fix(i2c): prevent unused variable and functions
  libraries/Wire/src/utility/twi.c
Labels: Enhancement, Fix

#2254 HardwareSerial's flush() method to override the method of the base class Print
  cores/arduino/HardwareSerial.cpp
  cores/arduino/HardwareSerial.h
Labels: Arduino compatibility, Fix

#2256 Fix compiler warning on HardwareTimer
  libraries/SrcWrapper/src/HardwareTimer.cpp
Labels: Fix
