Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2024-04, with the labels that each got.

#2326 fix(backup): update to support STM32C0xx
  cores/arduino/stm32/backup.h
Labels: Fix

#2347 Initial support for Nucleo-F439ZI
  README.md
  boards.txt
  variants/STM32F4xx/F427Z(G-I)T_F429ZET_F429Z(G-I)(T-Y)_F437Z(G-I)T_F439Z(G-I)(T-Y)/ldscript.ld
  variants/STM32F4xx/F427Z(G-I)T_F429ZET_F429Z(G-I)(T-Y)_F437Z(G-I)T_F439Z(G-I)(T-Y)/variant_NUCLEO_F4x9ZI.cpp
  variants/STM32F4xx/F427Z(G-I)T_F429ZET_F429Z(G-I)(T-Y)_F437Z(G-I)T_F439Z(G-I)(T-Y)/variant_NUCLEO_F4x9ZI.h
Labels: New variant

#2354 chore(wb): update to latest STM32CubeWB v1.19.0
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Include/stm32wbxx.h
  system/Drivers/CMSIS/Device/ST/STM32WBxx/LICENSE.md
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Release_Notes.html
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/startup_stm32wb10xx_cm4.s
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/startup_stm32wb15xx_cm4.s
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/startup_stm32wb1mxx_cm4.s
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/startup_stm32wb30xx_cm4.s
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/startup_stm32wb35xx_cm4.s
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/startup_stm32wb50xx_cm4.s
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/startup_stm32wb55xx_cm4.s
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/startup_stm32wb5mxx_cm4.s
  system/Drivers/CMSIS/Device/ST/STM32YYxx_CMSIS_version.md
  system/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_cortex.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_cryp.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_qspi.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_spi_ex.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_tim.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_rtc.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_tim.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_utils.h
  system/Drivers/STM32WBxx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_cortex.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_crc.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_cryp.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_gpio.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_i2c.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_qspi.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_smbus.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_spi_ex.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_tim.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
  variants/STM32WBxx/WB10CCU/PeripheralPins.c
  variants/STM32WBxx/WB15CCU/PeripheralPins.c
  variants/STM32WBxx/WB15CCUxE/PeripheralPins.c
  variants/STM32WBxx/WB15CCY/PeripheralPins.c
  variants/STM32WBxx/WB1MMCH/PeripheralPins.c
  variants/STM32WBxx/WB30CEUxA_WB50CGU/PeripheralPins.c
  variants/STM32WBxx/WB35C(C-E)UxA_WB55C(C-E-G)U/PeripheralPins.c
  variants/STM32WBxx/WB55R(C-E-G)V/PeripheralPins.c
  variants/STM32WBxx/WB55V(C-E-G)(Q-Y)_WB55VYY/PeripheralPins.c
  variants/STM32WBxx/WB5MMGH/PeripheralPins.c
Labels: Enhancement, Fix

#2353 chore(wba): update to latest STM32CubeWBA v1.3.1
  system/Drivers/CMSIS/Device/ST/STM32WBAxx/Include/stm32wba50xx.h
  system/Drivers/CMSIS/Device/ST/STM32WBAxx/Include/stm32wba52xx.h
  system/Drivers/CMSIS/Device/ST/STM32WBAxx/Include/stm32wba54xx.h
  system/Drivers/CMSIS/Device/ST/STM32WBAxx/Include/stm32wba55xx.h
  system/Drivers/CMSIS/Device/ST/STM32WBAxx/Include/stm32wbaxx.h
  system/Drivers/CMSIS/Device/ST/STM32WBAxx/Release_Notes.html
  system/Drivers/CMSIS/Device/ST/STM32YYxx_CMSIS_version.md
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal_cortex.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal_flash.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal_i2c_ex.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal_lptim.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal_pwr.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal_rcc.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal_rcc_ex.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal_rng_ex.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal_rtc.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal_rtc_ex.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal_smbus_ex.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal_tim.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal_tim_ex.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal_tsc.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal_uart_ex.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal_usart.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_hal_usart_ex.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_ll_adc.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_ll_cortex.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_ll_i2c.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_ll_lptim.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_ll_lpuart.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_ll_rtc.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_ll_tim.h
  system/Drivers/STM32WBAxx_HAL_Driver/Inc/stm32wbaxx_ll_usart.h
  system/Drivers/STM32WBAxx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal.c
  system/Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_adc.c
  system/Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_cortex.c
  system/Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_flash_ex.c
  system/Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_i2c.c
  system/Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_rcc_ex.c
  system/Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_rng_ex.c
  system/Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_rtc.c
  system/Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_smbus.c
  system/Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_smbus_ex.c
  system/Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_tim.c
  system/Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_tim_ex.c
  system/Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_tsc.c
  system/Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_ll_adc.c
  system/Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_ll_rtc.c
  system/Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_ll_tim.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
  variants/STM32WBAxx/WBA50K(E-G)U/PeripheralPins.c
  variants/STM32WBAxx/WBA52C(E-G)U_WBA54C(E-G)U_WBA55H(E-G)F/PeripheralPins.c
  variants/STM32WBAxx/WBA52K(E-G)U_WBA54K(E-G)U/PeripheralPins.c
  variants/STM32WBAxx/WBA55C(E-G)U/PeripheralPins.c
  variants/STM32WBAxx/WBA55U(E-G)I/PeripheralPins.c
Labels: Enhancement, Fix
