Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2024-09, with the labels that each got.

#2506 Fix H563ZI clock config.
  variants/STM32H5xx/H563Z(G-I)T_H573ZIT/generic_clock.c
  variants/STM32H5xx/H563Z(G-I)T_H573ZIT/variant_NUCLEO_H563ZI.cpp
Labels: enhancement

#2509 fix(h5): disable cache during DAC channel configuration
  libraries/SrcWrapper/src/stm32/analog.cpp
Labels: fix :adhesive_bandage:

#2507 Optimize H573RI/H503KB/H503RB clock config.
  variants/STM32H5xx/H503KBU/generic_clock.c
  variants/STM32H5xx/H503RBT/generic_clock.c
  variants/STM32H5xx/H503RBT/variant_NUCLEO_H503RB.cpp
  variants/STM32H5xx/H563R(G-I)T_H573RIT/generic_clock.c
Labels: fix :adhesive_bandage:

#2512 fix(boards.txt): use pid.0 instead of pid for Blues Cygnet
  boards.txt
Labels: fix :adhesive_bandage:

#2525 fix: Blues vid/pid couple
  boards.txt
Labels: arduino compatibility, fix :adhesive_bandage:
