Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2024-07, with the labels that each got.

#2414 fix: ELV_Modular_System upload options
  boards.txt
Labels: Fix

#2423 Add variant: Generic H503KBU
  README.md
  boards.txt
  variants/STM32H5xx/H503KBU/generic_clock.c
  variants/STM32H5xx/H503KBU/ldscript.ld
Labels: New variant

#2424 Add variant: Generic H563RGT, H563RIT, H573RIT
  README.md
  boards.txt
  variants/STM32H5xx/H563R(G-I)T_H573RIT/generic_clock.c
  variants/STM32H5xx/H563R(G-I)T_H573RIT/ldscript.ld
Labels: New variant

#2427 Generic L431C(B-C)(T-U) Variant
  README.md
  boards.txt
  variants/STM32L4xx/L431C(B-C)(T-U)/generic_clock.c
  variants/STM32L4xx/L431C(B-C)(T-U)/ldscript.ld
Labels: New variant

#2440 fix(upload_vid): wrong definitions
  boards.txt
  platform.txt
Labels: Bug :bug:, Fix

#2435 Add single buffer mode option to USB CDC to fix off-by-one corruption
  libraries/USBDevice/src/usbd_ep_conf.c
Labels: Enhancement

#2442 Fix Wire memory leak
  libraries/Wire/src/Wire.cpp
Labels: enhancement

#2449 fix(platform): core reference broken
  platform.txt
Labels: fix :adhesive_bandage:

#2453 fix(cmake): remove .elf extension from generated .bin and .hex
  cmake/convert_file.cmake
Labels: fix :adhesive_bandage:

#2454 fix(platform.txt): add default vid/pid definition
  boards.txt
  cmake/scripts/update_boarddb.py
  platform.txt
Labels: fix :adhesive_bandage:

#2458 fix: cleanup old debug configuration
  platform.txt
  system/extras/postbuild.sh
Labels: fix :adhesive_bandage:

#2421 chore(wb): update to latest STM32CubeWB v1.20.0
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Include/stm32wbxx.h
  system/Drivers/CMSIS/Device/ST/STM32WBxx/README.md
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Release_Notes.html
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/linker/stm32wb10xx_flash_cm4.ld
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/linker/stm32wb15xx_flash_cm4.ld
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/linker/stm32wb1mxx_flash_cm4.ld
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/linker/stm32wb30xx_flash_cm4.ld
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/linker/stm32wb35xx_flash_cm4.ld
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/linker/stm32wb50xx_flash_cm4.ld
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/linker/stm32wb55xx_flash_cm4.ld
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/linker/stm32wb5mxx_flash_cm4.ld
  system/Drivers/CMSIS/Device/ST/STM32YYxx_CMSIS_version.md
  system/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_comp.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_uart.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_lpuart.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_rng.h
  system/Drivers/STM32WBxx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_comp.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_i2c.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_smbus_ex.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart_ex.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_comp.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_rng.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
  variants/STM32WBxx/WB10CCU/PeripheralPins.c
  variants/STM32WBxx/WB15CCU/PeripheralPins.c
  variants/STM32WBxx/WB15CCUxE/PeripheralPins.c
  variants/STM32WBxx/WB15CCY/PeripheralPins.c
  variants/STM32WBxx/WB1MMCH/PeripheralPins.c
  variants/STM32WBxx/WB30CEUxA_WB50CGU/PeripheralPins.c
  variants/STM32WBxx/WB35C(C-E)UxA_WB55C(C-E-G)U/PeripheralPins.c
  variants/STM32WBxx/WB55R(C-E-G)V/PeripheralPins.c
  variants/STM32WBxx/WB55V(C-E-G)(Q-Y)_WB55VYY/PeripheralPins.c
  variants/STM32WBxx/WB5MMGH/PeripheralPins.c
Labels: enhancement, fix :adhesive_bandage:
