Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2024-05, with the labels that each got.

#2373 Added Support for ELV-BM-TRX1
  .github/workflows/MarkdwonLinksCheck.yml
  README.md
  boards.txt
  cmake/boards_db.cmake
  variants/STM32WLxx/WL54JCI_WL55JCI_WLE4J(8-B-C)I_WLE5J(8-B-C)I/CMakeLists.txt
  variants/STM32WLxx/WL54JCI_WL55JCI_WLE4J(8-B-C)I_WLE5J(8-B-C)I/PeripheralPins_ELV_BM_TRX1.c
  variants/STM32WLxx/WL54JCI_WL55JCI_WLE4J(8-B-C)I_WLE5J(8-B-C)I/variant_ELV_BM_TRX1.cpp
  variants/STM32WLxx/WL54JCI_WL55JCI_WLE4J(8-B-C)I_WLE5J(8-B-C)I/variant_ELV_BM_TRX1.h
Labels: New variant

#2379 fix(codespell): ignore new words
  CI/codespell/.codespellignore
Labels: Fix

#2359 Adding support for stm32c011j4m6
  README.md
  boards.txt
  variants/STM32C0xx/C011J(4-6)M/generic_clock.c
  variants/STM32C0xx/C011J(4-6)M/ldscript.ld
Labels: New variant

#2380 chore(system): define USE_HAL_DRIVER on command line
  CI/update/templates/system_stm32yyxx.c
  cmake/set_base_arduino_config.cmake
  cores/arduino/stm32/stm32_def.h
  libraries/SrcWrapper/src/stm32/system_stm32yyxx.c
  platform.txt
  tools/platformio/platformio-build.py
Labels: Enhancement, Fix

#2384 feat: support stm32 assert
  cores/arduino/stm32/stm32_assert.h
  cores/arduino/stm32/stm32_def.h
  libraries/SrcWrapper/src/stm32/stm32_def.c
Labels: Enhancement
