Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2024-08, with the labels that each got.

#2481 Sync PlatformIO build script
  tools/platformio/platformio-build.py
Labels: enhancement

#2482 Sync PlatformIO build script
  tools/platformio/platformio-build.py
Labels: enhancement

#2493 fix(wire): support only 7 bits addressing mode
  libraries/Wire/src/Wire.cpp
  libraries/Wire/src/utility/twi.c
  libraries/Wire/src/utility/twi.h
Labels: arduino compatibility

#2502 Remove atomicity warning that does not apply to STM32
  .github/PULL_REQUEST_TEMPLATE.md
  cores/arduino/HardwareSerial.h
Labels: documentation :books:, fix :adhesive_bandage:
