Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2024-03, with the labels that each got.

#2283 Multiple sketch support
  cmake/build_sketch.cmake
  cmake/sketch_preprocess_sources.cmake
Labels: Enhancement, New feature

#2309 Adding an option to disable DAC output buffer
  libraries/SrcWrapper/src/stm32/analog.cpp
Labels: Enhancement

#2315 chore: update xpack arm-none-eabi-gcc and openocd versions
  platform.txt
Labels: Enhancement, Fix

#2318 Fix issue with writing inital servo value before min/max is configured
  libraries/Servo/src/stm32/Servo.cpp
Labels: Bug :bug:, Fix

#2306 add "toString" function with IPAddress
  cores/arduino/IPAddress.cpp
  cores/arduino/IPAddress.h
Labels: Enhancement, Arduino compatibility

#2320 refactor(platform): factorize using variables
  platform.txt
  system/extras/postbuild.sh
  system/extras/prebuild.sh
Labels: Enhancement, Arduino compatibility
