Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2024-06, with the labels that each got.

#2401 chore: cmake enhancement
  cmake/boards_db.cmake
  cmake/scripts/ccwrapper.py
  cmake/scripts/cmake_easy_setup.py
  cmake/scripts/cmake_gen.py
  cmake/scripts/cmake_updater_hook.py
  cmake/scripts/generate_header.py
  cmake/scripts/includes.py
  cmake/scripts/sizereport.py
  cmake/scripts/syms.py
  cmake/scripts/update_boarddb.py
  cmake/templates/easy_cmake.cmake
  variants/STM32WLxx/WL54JCI_WL55JCI_WLE4J(8-B-C)I_WLE5J(8-B-C)I/CMakeLists.txt
Labels: Enhancement, Fix

#2323 refactor(STM32CubeProgrammer): rework options
  boards.txt
  cmake/boards_db.cmake
  platform.txt
Labels: Enhancement, Arduino compatibility, Fix

#2406 chore(f4): update to latest STM32CubeF4 v1.28.1
  system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f412cx.h
  system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h
  system/Drivers/CMSIS/Device/ST/STM32F4xx/Release_Notes.html
  system/Drivers/CMSIS/Device/ST/STM32YYxx_CMSIS_version.md
  system/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_conf_template.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_cortex.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dsi.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_eth.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash_ex.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash_ramfunc.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_lptim.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pcd_ex.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_qspi.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc_ex.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_spi.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_adc.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_bus.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_cortex.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_dma.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_rcc.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_spi.h
  system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_utils.h
  system/Drivers/STM32F4xx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dsi.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s_ex.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_qspi.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rcc.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_spi.c
  system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: Enhancement, Fix

#2405 Define generic boards for STM32L051K8U and -T
  README.md
  boards.txt
  variants/STM32L0xx/L051K(6-8)T/generic_clock.c
  variants/STM32L0xx/L051K(6-8)T/ldscript.ld
  variants/STM32L0xx/L051K(6-8)U/generic_clock.c
  variants/STM32L0xx/L051K(6-8)U/ldscript.ld
Labels: New variant
