Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2025-02, with the labels that each got.

#2647 Update wrong HSE value on variant_B_G431B_ESC1.h
  variants/STM32G4xx/G431C(6-8-B)U_G441CBU/variant_B_G431B_ESC1.h
Labels: fix :adhesive_bandage:

#2648 Add STM32F042K6Ux Variants
  README.md
  boards.txt
  variants/STM32F0xx/F042K(4-6)U/generic_clock.c
  variants/STM32F0xx/F042K(4-6)U/ldscript.ld
Labels: new variant

#2651 chore(uart): set LSE as source only if LSE is ready
  libraries/SrcWrapper/src/stm32/uart.c
Labels: enhancement

#2650 system(WL) update STM32WLxx HAL Drivers to v1.3.1
  system/Drivers/STM32WLxx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h
  system/Drivers/STM32WLxx_HAL_Driver/Inc/stm32wlxx_hal_cortex.h
  system/Drivers/STM32WLxx_HAL_Driver/Inc/stm32wlxx_hal_i2c.h
  system/Drivers/STM32WLxx_HAL_Driver/Inc/stm32wlxx_hal_smbus.h
  system/Drivers/STM32WLxx_HAL_Driver/Inc/stm32wlxx_ll_i2c.h
  system/Drivers/STM32WLxx_HAL_Driver/Inc/stm32wlxx_ll_utils.h
  system/Drivers/STM32WLxx_HAL_Driver/LICENSE.md
  system/Drivers/STM32WLxx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal.c
  system/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_adc.c
  system/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cortex.c
  system/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cryp.c
  system/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dac_ex.c
  system/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_i2c.c
  system/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_smbus.c
  system/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_spi.c
  system/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_subghz.c
  system/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_tim.c
  system/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_uart.c
  system/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_uart_ex.c
  system/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_adc.c
  system/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_gpio.c
  system/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_tim.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: enhancement, fix :adhesive_bandage:

#2652 chore: xpack update
  boards.txt
  debugger/select_dapdirect.cfg
  platform.txt
  variants/STM32C0xx/C011J(4-6)M/generic_clock.c
Labels: enhancement

#2655 variants(wb): add generic WB55V(C-E-G) and WB55VYY
  README.md
  boards.txt
  variants/STM32WBxx/WB55V(C-E-G)(Q-Y)_WB55VYY/generic_clock.c
  variants/STM32WBxx/WB55V(C-E-G)(Q-Y)_WB55VYY/ldscript.ld
Labels: new variant

#2657 feat(debugger): set dapdirect_swd as default transport
  boards.txt
  platform.txt
Labels: enhancement

#2660 chore(usb): update to latest USB device and host mw
  libraries/USBDevice/inc/usbd_conf.h
  system/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Src/usbd_audio.c
  system/Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Src/usbd_customhid.c
  system/Middlewares/ST/STM32_USB_Device_Library/Class/DFU/Inc/usbd_dfu.h
  system/Middlewares/ST/STM32_USB_Device_Library/Class/DFU/Src/usbd_dfu.c
  system/Middlewares/ST/STM32_USB_Device_Library/Class/DFU/Src/usbd_dfu_media_template.c
  system/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc/usbd_msc_data.h
  system/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_data.c
  system/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.c
  system/Middlewares/ST/STM32_USB_Device_Library/Class/VIDEO/Inc/usbd_video.h
  system/Middlewares/ST/STM32_USB_Device_Library/Class/VIDEO/Src/usbd_video.c
  system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_conf_template.h
  system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_core.h
  system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_def.h
  system/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
  system/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c
  system/Middlewares/ST/STM32_USB_Device_Library/Release_Notes.html
  system/Middlewares/ST/STM32_USB_Host_Library/Class/AUDIO/Inc/usbh_audio.h
  system/Middlewares/ST/STM32_USB_Host_Library/Class/AUDIO/Src/usbh_audio.c
  system/Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc/usbh_cdc.h
  system/Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Src/usbh_cdc.c
  system/Middlewares/ST/STM32_USB_Host_Library/Class/HID/Inc/usbh_hid.h
  system/Middlewares/ST/STM32_USB_Host_Library/Class/HID/Inc/usbh_hid_keybd.h
  system/Middlewares/ST/STM32_USB_Host_Library/Class/HID/Inc/usbh_hid_mouse.h
  system/Middlewares/ST/STM32_USB_Host_Library/Class/HID/Inc/usbh_hid_parser.h
  system/Middlewares/ST/STM32_USB_Host_Library/Class/HID/Inc/usbh_hid_usage.h
  system/Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src/usbh_hid.c
  system/Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src/usbh_hid_keybd.c
  system/Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src/usbh_hid_mouse.c
  system/Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src/usbh_hid_parser.c
  system/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc/usbh_msc.h
  system/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc/usbh_msc_bot.h
  system/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc/usbh_msc_scsi.h
  system/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc.c
  system/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc_bot.c
  system/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc_scsi.c
  system/Middlewares/ST/STM32_USB_Host_Library/Class/MTP/Inc/usbh_mtp.h
  system/Middlewares/ST/STM32_USB_Host_Library/Class/MTP/Inc/usbh_mtp_ptp.h
  system/Middlewares/ST/STM32_USB_Host_Library/Class/MTP/Src/usbh_mtp.c
  system/Middlewares/ST/STM32_USB_Host_Library/Class/MTP/Src/usbh_mtp_ptp.c
  system/Middlewares/ST/STM32_USB_Host_Library/Class/Template/Inc/usbh_template.h
  system/Middlewares/ST/STM32_USB_Host_Library/Class/Template/Src/usbh_template.c
  system/Middlewares/ST/STM32_USB_Host_Library/Core/Inc/usbh_conf_template.h
  system/Middlewares/ST/STM32_USB_Host_Library/Core/Inc/usbh_core.h
  system/Middlewares/ST/STM32_USB_Host_Library/Core/Inc/usbh_ctlreq.h
  system/Middlewares/ST/STM32_USB_Host_Library/Core/Inc/usbh_def.h
  system/Middlewares/ST/STM32_USB_Host_Library/Core/Inc/usbh_ioreq.h
  system/Middlewares/ST/STM32_USB_Host_Library/Core/Inc/usbh_pipes.h
  system/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_conf_template.c
  system/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_core.c
  system/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ctlreq.c
  system/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ioreq.c
  system/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_pipes.c
  system/Middlewares/ST/STM32_USB_Host_Library/LICENSE.md
  system/Middlewares/ST/STM32_USB_Host_Library/Release_Notes.html
Labels: enhancement, fix :adhesive_bandage:
