Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2025-03, with the labels that each got.

#2665 fix(doc): typo
  README.md
Labels: documentation :books:, fix :adhesive_bandage:

#2670 system(c0) update STM32C0xx HAL Drivers to v1.4.0
  system/Drivers/STM32C0xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h
  system/Drivers/STM32C0xx_HAL_Driver/Inc/stm32c0xx_ll_usart.h
  system/Drivers/STM32C0xx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32C0xx_HAL_Driver/Src/stm32c0xx_hal.c
  system/Drivers/STM32C0xx_HAL_Driver/Src/stm32c0xx_hal_adc_ex.c
  system/Drivers/STM32C0xx_HAL_Driver/Src/stm32c0xx_hal_rcc.c
  system/Drivers/STM32C0xx_HAL_Driver/Src/stm32c0xx_hal_tim.c
  system/Drivers/STM32C0xx_HAL_Driver/Src/stm32c0xx_hal_uart.c
  system/Drivers/STM32C0xx_HAL_Driver/Src/stm32c0xx_hal_uart_ex.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: enhancement, fix :adhesive_bandage:

#2672 system(WB) update STM32WBxx HAL Drivers to v1.14.5
  system/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_hsem.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_rtc.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_rtc_ex.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_tim.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_uart.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_hsem.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_lpuart.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_rtc.h
  system/Drivers/STM32WBxx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rtc.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rtc_ex.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_tim.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart_ex.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_rtc.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: enhancement, fix :adhesive_bandage:

#2684 fix(openocd): update to xpack-openocd v0.12.0-6
  platform.txt
Labels: fix :adhesive_bandage:

#2688 Update stm32_def.h
  libraries/SrcWrapper/inc/stm32_def.h
Labels: fix :adhesive_bandage:

#2693 fix(f7): PLLR value
  variants/STM32F7xx/F765V(G-I)(H-T)_F767V(G-I)(H-T)_F777VI(H-T)/generic_clock.c
  variants/STM32F7xx/F765V(G-I)(H-T)_F767V(G-I)(H-T)_F777VI(H-T)/variant_REMRAM_V1.cpp
  variants/STM32F7xx/F765Z(G-I)T_F767Z(G-I)T_F777ZIT/generic_clock.c
  variants/STM32F7xx/F765Z(G-I)T_F767Z(G-I)T_F777ZIT/variant_NUCLEO_F767ZI.cpp
Labels: fix :adhesive_bandage:

#2695 Tidying up clock config of H5.
  variants/STM32H5xx/H503CB(T-U)/generic_clock.c
  variants/STM32H5xx/H503KBU/generic_clock.c
  variants/STM32H5xx/H503RBT/generic_clock.c
  variants/STM32H5xx/H503RBT/variant_NUCLEO_H503RB.cpp
  variants/STM32H5xx/H503RBT/variant_NUCLEO_H503RB.h
  variants/STM32H5xx/H562R(G-I)T/generic_clock.c
  variants/STM32H5xx/H562R(G-I)T/variant_WEACT_H562RG.cpp
  variants/STM32H5xx/H562R(G-I)T/variant_WEACT_H562RG.h
  variants/STM32H5xx/H563IIKxQ_H573IIKxQ/generic_clock.c
  variants/STM32H5xx/H563IIKxQ_H573IIKxQ/variant_STM32H573I_DK.cpp
  variants/STM32H5xx/H563R(G-I)T_H573RIT/generic_clock.c
  variants/STM32H5xx/H563Z(G-I)T_H573ZIT/generic_clock.c
  variants/STM32H5xx/H563Z(G-I)T_H573ZIT/variant_NUCLEO_H563ZI.cpp
  variants/STM32H5xx/H563Z(G-I)T_H573ZIT/variant_NUCLEO_H563ZI.h
Labels: enhancement
