Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2025-04, with the labels that each got.

#2714 fix: broken url
  .github/workflows/MarkdwonLinksCheck.yml
  README.md
Labels: enhancement, fix :adhesive_bandage:

#2713 Variant addition: Nucleo-64 L412RB_P
  README.md
  boards.txt
  variants/STM32L4xx/L412RB(I-T)xP/CMakeLists.txt
  variants/STM32L4xx/L412RB(I-T)xP/ldscript.ld
  variants/STM32L4xx/L412RB(I-T)xP/variant_NUCLEO_L412RB_P.cpp
  variants/STM32L4xx/L412RB(I-T)xP/variant_NUCLEO_L412RB_P.h
Labels: new variant

#2712 feat (uart): implement proper operator bool()
  cores/arduino/HardwareSerial.cpp
  cores/arduino/HardwareSerial.h
  libraries/SrcWrapper/inc/uart.h
  libraries/SrcWrapper/src/stm32/uart.c
Labels: enhancement

#2719 fix(uart): unused warnings
  libraries/SrcWrapper/src/stm32/uart.c
Labels: fix :adhesive_bandage:
