Repository stm32duino/Arduino_Core_STM32, pull requests merged in 2025-07, with the labels that each got.

#2758 fix(Wire): only recover bus when device is master
  libraries/Wire/src/Wire.cpp
Labels: fix :adhesive_bandage:

#2769 chore(wb): update to latest STM32CubeWB v1.23.0
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Include/stm32wb10xx.h
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Include/stm32wb15xx.h
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Include/stm32wb1mxx.h
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Include/stm32wb30xx.h
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Include/stm32wb35xx.h
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Include/stm32wb50xx.h
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Include/stm32wb55xx.h
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Include/stm32wb5mxx.h
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Include/stm32wbxx.h
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Release_Notes.html
  system/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/system_stm32wbxx.c
  system/Drivers/CMSIS/Device/ST/STM32YYxx_CMSIS_version.md
  system/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_lptim.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_smartcard.h
  system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_ll_iwdg.h
  system/Drivers/STM32WBxx_HAL_Driver/Release_Notes.html
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_i2c.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_iwdg.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pcd.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rtc.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_smartcard.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_smbus.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_spi.c
  system/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_usb.c
  system/Drivers/STM32YYxx_HAL_Driver_version.md
Labels: enhancement, fix :adhesive_bandage:

#2775 feat: add STM32U073C(8-B-C) and STM32U083CC generic board support
  README.md
  boards.txt
  variants/STM32U0xx/U073C(8-B-C)(T-U)_U083CC(T-U)/generic_clock.c
  variants/STM32U0xx/U073C(8-B-C)(T-U)_U083CC(T-U)/ldscript.ld
Labels: new variant
